//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsOrganizational
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaViTri
    {
        public int IDMaViTri { get; set; }
        public string TenMaViTri { get; set; }
        public Nullable<int> IDLoai { get; set; }
    }
}
