//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsOrganizational
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienPVSX
    {
        public int IDNV { get; set; }
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public Nullable<int> IDViTri { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> TT_BGD { get; set; }
    
        public virtual ViTri ViTri { get; set; }
    }
}
