//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsOrganizational
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomLV
    {
        public int IDNhom { get; set; }
        public string TenNhom { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public Nullable<int> IDNhomPT { get; set; }
        public Nullable<int> PTDB { get; set; }
        public Nullable<int> KTVDB { get; set; }
        public Nullable<int> NVDB { get; set; }
        public Nullable<int> KTVCa { get; set; }
        public Nullable<int> NVCa { get; set; }
        public Nullable<int> TPTDB { get; set; }
        public Nullable<int> TPKipDB { get; set; }
        public Nullable<int> TTTPDB { get; set; }
    }
}
