//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsOrganizational
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanXuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhanXuong()
        {
            this.NhanVienAPIs = new HashSet<NhanVienAPI>();
        }
    
        public int IDPhanXuong { get; set; }
        public string TenPhanXuong { get; set; }
        public Nullable<int> PhongBanID { get; set; }
        public Nullable<int> PTDB { get; set; }
        public Nullable<int> TPDB { get; set; }
        public Nullable<int> KTVDB { get; set; }
        public Nullable<int> NVDB { get; set; }
        public Nullable<int> NVHCDB { get; set; }
        public Nullable<int> TPTT { get; set; }
        public Nullable<int> KTVTT { get; set; }
        public Nullable<int> NVTT { get; set; }
        public Nullable<int> TPKip { get; set; }
        public Nullable<int> TTTPDB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVienAPI> NhanVienAPIs { get; set; }
    }
}
