//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsOrganizational
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToLV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToLV()
        {
            this.NhanVienAPIs = new HashSet<NhanVienAPI>();
        }
    
        public int IDTo { get; set; }
        public string TenTo { get; set; }
        public Nullable<int> PhanXuongID { get; set; }
        public Nullable<int> PhongBanID { get; set; }
        public Nullable<int> SLDB { get; set; }
        public Nullable<int> IDNhomPT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVienAPI> NhanVienAPIs { get; set; }
    }
}
