
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class AuthorizationVideo
{

    public int ID { get; set; }

    public Nullable<int> NhanVienID { get; set; }

    public Nullable<System.DateTime> Createdate { get; set; }

    public Nullable<int> VideoID { get; set; }



    public virtual NhanVien NhanVien { get; set; }

    public virtual Video Video { get; set; }

}

}
