
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class Calender
{

    public int IDPlan { get; set; }

    public Nullable<int> IDCalendar { get; set; }

    public string LongName { get; set; }

    public string ShortName { get; set; }

    public Nullable<int> PhongBanID { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string Image { get; set; }

    public string Note { get; set; }

    public Nullable<int> Status { get; set; }

}

}
