
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class DangKy
{

    public int IDDK { get; set; }

    public string TenDangNhap { get; set; }

    public string MatKhau { get; set; }

    public string MaNV { get; set; }

    public string HoTen { get; set; }

    public string Email { get; set; }

    public Nullable<int> MaQuyen { get; set; }

    public Nullable<int> IDPhongBan { get; set; }

}

}
