
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class KD_KyDuyet
{

    public int IDKD { get; set; }

    public Nullable<int> IDNhanVien { get; set; }

    public string GhiChu { get; set; }

    public int IDLoaiKD { get; set; }



    public virtual KD_LoaiKyDuyet KD_LoaiKyDuyet { get; set; }

    public virtual NhanVien NhanVien { get; set; }

}

}
