
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class KD_TrinhKyGH
{

    public int IDTKGH { get; set; }

    public Nullable<int> IDGH { get; set; }

    public Nullable<int> IDKTV { get; set; }

    public Nullable<int> TKKTV { get; set; }

    public string GhiChuKTV { get; set; }

    public Nullable<System.DateTime> NgayKyKTV { get; set; }

    public Nullable<int> IDBPQL { get; set; }

    public Nullable<int> TKBPQL { get; set; }

    public string GhiChuBPQL { get; set; }

    public Nullable<System.DateTime> NgayKyBPQL { get; set; }

    public Nullable<int> IDVP1C { get; set; }

    public Nullable<int> TKVP1C { get; set; }

    public string GhiChuVP1C { get; set; }

    public Nullable<System.DateTime> NgayKyVP1C { get; set; }

}

}
