
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class KhaiBao_VoChong
{

    public int VoChongID { get; set; }

    public string TenVoChong { get; set; }

    public Nullable<int> NamSinhVoChong { get; set; }

    public string MaNhanVien { get; set; }

}

}
