
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class KhaiBao_ConCai
{

    public int ConCaiID { get; set; }

    public string TenCon { get; set; }

    public Nullable<int> NamSinhCon { get; set; }

    public string GiayKhaiSinh { get; set; }

    public string MaNhanVien { get; set; }

}

}
