
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class KhaiBao_NhanVien
{

    public int KhaiBaoID { get; set; }

    public string MaNhanVien { get; set; }

    public string TenNhanVien { get; set; }

    public Nullable<short> LoaiKhaiBao { get; set; }

    public Nullable<bool> DaXacNhan { get; set; }

    public Nullable<System.DateTime> NgayKhaiBao { get; set; }

}

}
