
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class NT_Contract
{

    public int IDContract { get; set; }

    public string Somecontracts { get; set; }

    public string Contract { get; set; }

    public Nullable<System.DateTime> BeginDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public string FileScan { get; set; }

    public Nullable<int> IDNT { get; set; }

    public Nullable<int> IDBP { get; set; }

    public Nullable<int> TPBP { get; set; }

    public Nullable<int> TTXL { get; set; }

}

}
