
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class NT_CardRegistrationInfor
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NT_CardRegistrationInfor()
    {

        this.KD_TrinhKy = new HashSet<KD_TrinhKy>();

        this.NT_DetailCardRegistrationInfor = new HashSet<NT_DetailCardRegistrationInfor>();

    }


    public int IDDS { get; set; }

    public string Contents { get; set; }

    public string Namefile { get; set; }

    public Nullable<int> ContractorsID { get; set; }

    public Nullable<int> ContractID { get; set; }

    public Nullable<int> PhongBanID { get; set; }

    public Nullable<System.DateTime> DayUpload { get; set; }

    public string Note { get; set; }

    public Nullable<int> IDNVTK { get; set; }

    public string FileComplete { get; set; }

    public Nullable<int> IDTTTK { get; set; }

    public Nullable<System.DateTime> DaySchool { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KD_TrinhKy> KD_TrinhKy { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NT_DetailCardRegistrationInfor> NT_DetailCardRegistrationInfor { get; set; }

}

}
