
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class NT_DetailCardRegistrationInfor
{

    public int IDCT { get; set; }

    public string FullName { get; set; }

    public string CCCD { get; set; }

    public Nullable<System.DateTime> BirthDay { get; set; }

    public string PermanentResidence { get; set; }

    public Nullable<int> Position { get; set; }

    public string Phone { get; set; }

    public string PhoneInformation { get; set; }

    public string StorageCard { get; set; }

    public string AccessCard { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<int> IDCA { get; set; }

    public string IDKV { get; set; }

    public Nullable<int> IDGroup { get; set; }

    public string IDGate { get; set; }

    public string Note { get; set; }

    public Nullable<int> IDDS { get; set; }

    public Nullable<int> InOutID { get; set; }

    public Nullable<int> ResultID { get; set; }



    public virtual NT_CardRegistrationInfor NT_CardRegistrationInfor { get; set; }

}

}
