
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class NT_Extendcard
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NT_Extendcard()
    {

        this.NT_DetailExtendcard = new HashSet<NT_DetailExtendcard>();

    }


    public int IDGH { get; set; }

    public string NoiDung { get; set; }

    public string Namefile { get; set; }

    public Nullable<int> NTID { get; set; }

    public Nullable<int> HDID { get; set; }

    public Nullable<int> PhongBanID { get; set; }

    public Nullable<System.DateTime> NgayTrinhKy { get; set; }

    public string GhiChu { get; set; }

    public Nullable<int> IDTTTK { get; set; }

    public Nullable<int> IDNVTK { get; set; }

    public string FileComplete { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NT_DetailExtendcard> NT_DetailExtendcard { get; set; }

}

}
