
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsView360
{

using System;
    using System.Collections.Generic;
    
public partial class NT_Partner
{

    public int ID { get; set; }

    public Nullable<int> BPID { get; set; }

    public string FullName { get; set; }

    public string Taxcode { get; set; }

    public string Address { get; set; }

    public string Customer { get; set; }

    public string Vendor { get; set; }

    public string Email { get; set; }

    public string ShortName { get; set; }

    public string CodeUnis { get; set; }

}

}
