//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsTagSign
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDNT_XeCoDong
    {
        public int ID { get; set; }
        public Nullable<int> ID_NT { get; set; }
        public Nullable<int> BP_ID { get; set; }
        public string TenNhaThau { get; set; }
        public string TenDayDu { get; set; }
        public string HoVaTen { get; set; }
        public string CMND_CCCD { get; set; }
        public string BienSoXe { get; set; }
        public string LoaiPhuongTien { get; set; }
        public string Hang { get; set; }
        public string Dong { get; set; }
        public string MauSac { get; set; }
        public string TuNgay { get; set; }
        public string DenNgay { get; set; }
    }
}
