//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsTagSign
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDNT_DinhBienXinThem
    {
        public int ID { get; set; }
        public Nullable<int> NhaThau_ID { get; set; }
        public Nullable<int> DinhBienXinThem_XeMay { get; set; }
        public Nullable<int> DinhBienXinThem_Xe3Gac { get; set; }
        public string GhiChu { get; set; }
        public string User_Edit { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
