//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsTagSign
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDNT_ChiTietDon
    {
        public int ID { get; set; }
        public string Ma_Don { get; set; }
        public Nullable<int> ID_LoaiPhuongTien { get; set; }
        public string BienSoXe { get; set; }
        public Nullable<bool> CapMoi { get; set; }
        public Nullable<bool> CapLai { get; set; }
        public Nullable<bool> GiaHan { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string GhiChu { get; set; }
        public string HoSoTheoXe { get; set; }
        public Nullable<int> TrangThaiDuyet_ID { get; set; }
        public Nullable<int> ID_NhaThau { get; set; }
    }
}
