
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsTagSign
{

using System;
    using System.Collections.Generic;
    
public partial class CollectMoney
{

    public int ID_PT { get; set; }

    public Nullable<int> DKTN_ID { get; set; }

    public Nullable<System.DateTime> NgayThu { get; set; }

    public string SoPhieuThu { get; set; }

    public Nullable<int> TongSoThe { get; set; }

    public string TongSoTien { get; set; }

}

}
