
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsTagSign
{

using System;
    using System.Collections.Generic;
    
public partial class Detail_RegisterPeople
{

    public int ID_CT_DKTN { get; set; }

    public Nullable<int> DKTN_ID { get; set; }

    public string HoVaTen { get; set; }

    public Nullable<System.DateTime> NgaySinh { get; set; }

    public string CCCD { get; set; }

    public string HoKhau { get; set; }

    public Nullable<int> CV_ID { get; set; }

    public string SoDienThoai { get; set; }

    public string Ten_NTP { get; set; }

    public string HoTen_QuanLy { get; set; }

    public string SoDienThoai_QuanLy { get; set; }

    public string CapMoi { get; set; }

    public string GiaHan { get; set; }

    public string BoSungCong { get; set; }

    public string CapLai { get; set; }

    public string ChuyenNT { get; set; }

    public Nullable<System.DateTime> ThoiHanThe { get; set; }

    public string KhuVucLamViec { get; set; }

    public string CongLamViec { get; set; }

    public Nullable<int> NhomNT { get; set; }

    public string GhiChu { get; set; }

    public string Price { get; set; }

    public Nullable<int> DienThoaiThongMinh { get; set; }

    public string GhiChuHPDQ { get; set; }

}

}
