
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsTagSign
{

using System;
    using System.Collections.Generic;
    
public partial class DK_CardExtend
{

    public int IDGHT { get; set; }

    public string NoiDung { get; set; }

    public Nullable<int> NTID { get; set; }

    public Nullable<int> HDID { get; set; }

    public Nullable<int> PhongBanID { get; set; }

    public Nullable<System.DateTime> NgayDangKy { get; set; }

    public Nullable<int> NhanVienID { get; set; }

    public Nullable<int> TinhTrangID { get; set; }

    public string GhiChu { get; set; }

    public Nullable<int> LoaiNT { get; set; }

    public string FileComplete { get; set; }

}

}
