
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsTagSign
{

using System;
    using System.Collections.Generic;
    
public partial class DK_DetailCardExtend
{

    public int IDCTGH { get; set; }

    public string HoTen { get; set; }

    public Nullable<System.DateTime> NgaySinh { get; set; }

    public string CCCD { get; set; }

    public string HoKhau { get; set; }

    public Nullable<int> ChucVu { get; set; }

    public string SoDienThoai { get; set; }

    public string CapLai { get; set; }

    public string GiaHan { get; set; }

    public string ThongTinLuuTru { get; set; }

    public string DTTM { get; set; }

    public string RaVaoCang { get; set; }

    public Nullable<System.DateTime> ThoiHanThe { get; set; }

    public string KhuVucLamViec { get; set; }

    public string Cong { get; set; }

    public Nullable<int> NhomNT { get; set; }

    public string GhiChu { get; set; }

    public Nullable<int> IDGHT { get; set; }

}

}
