
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsTagSign
{

using System;
    using System.Collections.Generic;
    
public partial class Flow
{

    public int ID_XL { get; set; }

    public string TenXuLy { get; set; }

}

}
