//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsTagSign
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTNT_DonDangKy
    {
        public int ID { get; set; }
        public string MaDon { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> ID_NhaThau { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserNameLogin { get; set; }
        public Nullable<int> BP_XuLy_ID { get; set; }
        public string GhiChu { get; set; }
    }
}
