//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsTagSign
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTNT_ChiTiet
    {
        public int ID { get; set; }
        public string MaDon { get; set; }
        public string TN_HoTen { get; set; }
        public string TN_CCCD_HoChieu { get; set; }
        public Nullable<int> TX_LoaiXeCoDong { get; set; }
        public string TX_BienKiemSoat { get; set; }
        public string PT_LoaiPhuongTien { get; set; }
        public string PT_BienKiemSoat { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}
