
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsTagSign
{

using System;
    using System.Collections.Generic;
    
public partial class RegisterPeople
{

    public int ID_DKTN { get; set; }

    public string NoiDung { get; set; }

    public Nullable<int> BPQL_ID { get; set; }

    public Nullable<int> NhanVienNT_ID { get; set; }

    public Nullable<int> NhaThau_ID { get; set; }

    public string HopDong { get; set; }

    public Nullable<System.DateTime> NgayTrinhKy { get; set; }

    public string File_CCAT { get; set; }

    public string File_IMG { get; set; }

    public Nullable<int> TrinhKy_ID { get; set; }

    public Nullable<int> TinhTrang_ID { get; set; }

    public Nullable<int> LoaiNT_ID { get; set; }

}

}
