
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsTagSign
{

using System;
    using System.Collections.Generic;
    
public partial class TK_CardExtend
{

    public int IDTKGHT { get; set; }

    public Nullable<int> GHTID { get; set; }

    public Nullable<int> CapDuyet { get; set; }

    public Nullable<int> TinhTrangID { get; set; }

    public Nullable<int> NhanVienID { get; set; }

    public Nullable<System.DateTime> NgayDuyet { get; set; }

    public string GhiChu { get; set; }

}

}
