//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsDanhBaDoiTac
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DanhBaDoiTacEntities : DbContext
    {
        public DanhBaDoiTacEntities()
            : base("name=DanhBaDoiTacEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DB_DiaChi> DB_DiaChi { get; set; }
        public virtual DbSet<DB_HangMuc> DB_HangMuc { get; set; }
        public virtual DbSet<DB_KhieuNai> DB_KhieuNai { get; set; }
        public virtual DbSet<DB_LinhVucHoatDong> DB_LinhVucHoatDong { get; set; }
        public virtual DbSet<DB_LinhVucNB> DB_LinhVucNB { get; set; }
        public virtual DbSet<DB_LoaiDoiTac> DB_LoaiDoiTac { get; set; }
        public virtual DbSet<DB_NhanVien> DB_NhanVien { get; set; }
        public virtual DbSet<DB_PhanHoiDoiTac> DB_PhanHoiDoiTac { get; set; }
        public virtual DbSet<DB_PhongBan> DB_PhongBan { get; set; }
        public virtual DbSet<DB_Quyen> DB_Quyen { get; set; }
        public virtual DbSet<DB_ThongBao> DB_ThongBao { get; set; }
        public virtual DbSet<DB_ThongBao_DoiTac> DB_ThongBao_DoiTac { get; set; }
        public virtual DbSet<DB_TinhTrangKhieuNai> DB_TinhTrangKhieuNai { get; set; }
        public virtual DbSet<DB_TinhTrangThongBao> DB_TinhTrangThongBao { get; set; }
        public virtual DbSet<DB_TinTuc> DB_TinTuc { get; set; }
        public virtual DbSet<DB_TTDoiTac> DB_TTDoiTac { get; set; }
        public virtual DbSet<DB_Vitri> DB_Vitri { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<DB_Benefit> DB_Benefit { get; set; }
        public virtual DbSet<DB_IntroductTD> DB_IntroductTD { get; set; }
        public virtual DbSet<DB_Mission> DB_Mission { get; set; }
        public virtual DbSet<DB_Picture> DB_Picture { get; set; }
        public virtual DbSet<DB_TongQuan> DB_TongQuan { get; set; }
    
        public virtual int DB_DiaChi_delete(Nullable<int> iDDiaChi)
        {
            var iDDiaChiParameter = iDDiaChi.HasValue ?
                new ObjectParameter("IDDiaChi", iDDiaChi) :
                new ObjectParameter("IDDiaChi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_DiaChi_delete", iDDiaChiParameter);
        }
    
        public virtual int DB_DiaChi_insert(string diaChi, string mien)
        {
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var mienParameter = mien != null ?
                new ObjectParameter("Mien", mien) :
                new ObjectParameter("Mien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_DiaChi_insert", diaChiParameter, mienParameter);
        }
    
        public virtual ObjectResult<DB_DiaChi_searchByID_Result> DB_DiaChi_searchByID(Nullable<int> iDDiaChi)
        {
            var iDDiaChiParameter = iDDiaChi.HasValue ?
                new ObjectParameter("IDDiaChi", iDDiaChi) :
                new ObjectParameter("IDDiaChi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_DiaChi_searchByID_Result>("DB_DiaChi_searchByID", iDDiaChiParameter);
        }
    
        public virtual ObjectResult<DB_DiaChi_select_Result> DB_DiaChi_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_DiaChi_select_Result>("DB_DiaChi_select");
        }
    
        public virtual int DB_DiaChi_update(Nullable<int> iDDiaChi, string diaChi, string mien)
        {
            var iDDiaChiParameter = iDDiaChi.HasValue ?
                new ObjectParameter("IDDiaChi", iDDiaChi) :
                new ObjectParameter("IDDiaChi", typeof(int));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var mienParameter = mien != null ?
                new ObjectParameter("Mien", mien) :
                new ObjectParameter("Mien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_DiaChi_update", iDDiaChiParameter, diaChiParameter, mienParameter);
        }
    
        public virtual int DB_HangMuc_delete(Nullable<int> iDHangMuc)
        {
            var iDHangMucParameter = iDHangMuc.HasValue ?
                new ObjectParameter("IDHangMuc", iDHangMuc) :
                new ObjectParameter("IDHangMuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_HangMuc_delete", iDHangMucParameter);
        }
    
        public virtual int DB_HangMuc_insert(string maHM, string tenHangMuc, Nullable<System.DateTime> ngayKyHĐ, Nullable<int> linhVucHM_ID, Nullable<int> doiTacID)
        {
            var maHMParameter = maHM != null ?
                new ObjectParameter("MaHM", maHM) :
                new ObjectParameter("MaHM", typeof(string));
    
            var tenHangMucParameter = tenHangMuc != null ?
                new ObjectParameter("TenHangMuc", tenHangMuc) :
                new ObjectParameter("TenHangMuc", typeof(string));
    
            var ngayKyHĐParameter = ngayKyHĐ.HasValue ?
                new ObjectParameter("NgayKyHĐ", ngayKyHĐ) :
                new ObjectParameter("NgayKyHĐ", typeof(System.DateTime));
    
            var linhVucHM_IDParameter = linhVucHM_ID.HasValue ?
                new ObjectParameter("LinhVucHM_ID", linhVucHM_ID) :
                new ObjectParameter("LinhVucHM_ID", typeof(int));
    
            var doiTacIDParameter = doiTacID.HasValue ?
                new ObjectParameter("DoiTacID", doiTacID) :
                new ObjectParameter("DoiTacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_HangMuc_insert", maHMParameter, tenHangMucParameter, ngayKyHĐParameter, linhVucHM_IDParameter, doiTacIDParameter);
        }
    
        public virtual ObjectResult<DB_HangMuc_searchByID_Result> DB_HangMuc_searchByID(Nullable<int> iDHangMuc)
        {
            var iDHangMucParameter = iDHangMuc.HasValue ?
                new ObjectParameter("IDHangMuc", iDHangMuc) :
                new ObjectParameter("IDHangMuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_HangMuc_searchByID_Result>("DB_HangMuc_searchByID", iDHangMucParameter);
        }
    
        public virtual ObjectResult<DB_HangMuc_select_Result> DB_HangMuc_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_HangMuc_select_Result>("DB_HangMuc_select");
        }
    
        public virtual int DB_HangMuc_update(Nullable<int> iDHangMuc, string maHM, string tenHangMuc, Nullable<System.DateTime> ngayKyHĐ, Nullable<int> linhVucHM_ID, Nullable<int> doiTacID)
        {
            var iDHangMucParameter = iDHangMuc.HasValue ?
                new ObjectParameter("IDHangMuc", iDHangMuc) :
                new ObjectParameter("IDHangMuc", typeof(int));
    
            var maHMParameter = maHM != null ?
                new ObjectParameter("MaHM", maHM) :
                new ObjectParameter("MaHM", typeof(string));
    
            var tenHangMucParameter = tenHangMuc != null ?
                new ObjectParameter("TenHangMuc", tenHangMuc) :
                new ObjectParameter("TenHangMuc", typeof(string));
    
            var ngayKyHĐParameter = ngayKyHĐ.HasValue ?
                new ObjectParameter("NgayKyHĐ", ngayKyHĐ) :
                new ObjectParameter("NgayKyHĐ", typeof(System.DateTime));
    
            var linhVucHM_IDParameter = linhVucHM_ID.HasValue ?
                new ObjectParameter("LinhVucHM_ID", linhVucHM_ID) :
                new ObjectParameter("LinhVucHM_ID", typeof(int));
    
            var doiTacIDParameter = doiTacID.HasValue ?
                new ObjectParameter("DoiTacID", doiTacID) :
                new ObjectParameter("DoiTacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_HangMuc_update", iDHangMucParameter, maHMParameter, tenHangMucParameter, ngayKyHĐParameter, linhVucHM_IDParameter, doiTacIDParameter);
        }
    
        public virtual int DB_KhieuNai_delete(Nullable<int> iDKhieuNai)
        {
            var iDKhieuNaiParameter = iDKhieuNai.HasValue ?
                new ObjectParameter("IDKhieuNai", iDKhieuNai) :
                new ObjectParameter("IDKhieuNai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_KhieuNai_delete", iDKhieuNaiParameter);
        }
    
        public virtual int DB_KhieuNai_insert(string maKhieuNai, string noiDungKN, Nullable<int> iDDoiTac, string tieuDeKN, string fileDinhKem, string nguoiKN, Nullable<System.DateTime> ngayKN, Nullable<int> iDTTKN)
        {
            var maKhieuNaiParameter = maKhieuNai != null ?
                new ObjectParameter("MaKhieuNai", maKhieuNai) :
                new ObjectParameter("MaKhieuNai", typeof(string));
    
            var noiDungKNParameter = noiDungKN != null ?
                new ObjectParameter("NoiDungKN", noiDungKN) :
                new ObjectParameter("NoiDungKN", typeof(string));
    
            var iDDoiTacParameter = iDDoiTac.HasValue ?
                new ObjectParameter("IDDoiTac", iDDoiTac) :
                new ObjectParameter("IDDoiTac", typeof(int));
    
            var tieuDeKNParameter = tieuDeKN != null ?
                new ObjectParameter("TieuDeKN", tieuDeKN) :
                new ObjectParameter("TieuDeKN", typeof(string));
    
            var fileDinhKemParameter = fileDinhKem != null ?
                new ObjectParameter("FileDinhKem", fileDinhKem) :
                new ObjectParameter("FileDinhKem", typeof(string));
    
            var nguoiKNParameter = nguoiKN != null ?
                new ObjectParameter("NguoiKN", nguoiKN) :
                new ObjectParameter("NguoiKN", typeof(string));
    
            var ngayKNParameter = ngayKN.HasValue ?
                new ObjectParameter("NgayKN", ngayKN) :
                new ObjectParameter("NgayKN", typeof(System.DateTime));
    
            var iDTTKNParameter = iDTTKN.HasValue ?
                new ObjectParameter("IDTTKN", iDTTKN) :
                new ObjectParameter("IDTTKN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_KhieuNai_insert", maKhieuNaiParameter, noiDungKNParameter, iDDoiTacParameter, tieuDeKNParameter, fileDinhKemParameter, nguoiKNParameter, ngayKNParameter, iDTTKNParameter);
        }
    
        public virtual ObjectResult<DB_KhieuNai_searchByID_Result> DB_KhieuNai_searchByID(Nullable<int> iDKhieuNai)
        {
            var iDKhieuNaiParameter = iDKhieuNai.HasValue ?
                new ObjectParameter("IDKhieuNai", iDKhieuNai) :
                new ObjectParameter("IDKhieuNai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_KhieuNai_searchByID_Result>("DB_KhieuNai_searchByID", iDKhieuNaiParameter);
        }
    
        public virtual ObjectResult<DB_KhieuNai_select_Result> DB_KhieuNai_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_KhieuNai_select_Result>("DB_KhieuNai_select");
        }
    
        public virtual int DB_KhieuNai_update(Nullable<int> iDKhieuNai, string maKhieuNai, Nullable<int> iDDoiTac, string tieuDeKN, string noiDungKN, string fileDinhKem, string nguoiKN, Nullable<System.DateTime> ngayKN, Nullable<int> iDTTKN)
        {
            var iDKhieuNaiParameter = iDKhieuNai.HasValue ?
                new ObjectParameter("IDKhieuNai", iDKhieuNai) :
                new ObjectParameter("IDKhieuNai", typeof(int));
    
            var maKhieuNaiParameter = maKhieuNai != null ?
                new ObjectParameter("MaKhieuNai", maKhieuNai) :
                new ObjectParameter("MaKhieuNai", typeof(string));
    
            var iDDoiTacParameter = iDDoiTac.HasValue ?
                new ObjectParameter("IDDoiTac", iDDoiTac) :
                new ObjectParameter("IDDoiTac", typeof(int));
    
            var tieuDeKNParameter = tieuDeKN != null ?
                new ObjectParameter("TieuDeKN", tieuDeKN) :
                new ObjectParameter("TieuDeKN", typeof(string));
    
            var noiDungKNParameter = noiDungKN != null ?
                new ObjectParameter("NoiDungKN", noiDungKN) :
                new ObjectParameter("NoiDungKN", typeof(string));
    
            var fileDinhKemParameter = fileDinhKem != null ?
                new ObjectParameter("FileDinhKem", fileDinhKem) :
                new ObjectParameter("FileDinhKem", typeof(string));
    
            var nguoiKNParameter = nguoiKN != null ?
                new ObjectParameter("NguoiKN", nguoiKN) :
                new ObjectParameter("NguoiKN", typeof(string));
    
            var ngayKNParameter = ngayKN.HasValue ?
                new ObjectParameter("NgayKN", ngayKN) :
                new ObjectParameter("NgayKN", typeof(System.DateTime));
    
            var iDTTKNParameter = iDTTKN.HasValue ?
                new ObjectParameter("IDTTKN", iDTTKN) :
                new ObjectParameter("IDTTKN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_KhieuNai_update", iDKhieuNaiParameter, maKhieuNaiParameter, iDDoiTacParameter, tieuDeKNParameter, noiDungKNParameter, fileDinhKemParameter, nguoiKNParameter, ngayKNParameter, iDTTKNParameter);
        }
    
        public virtual int DB_KhieuNai_updateTinhTrang(Nullable<int> iDKhieuNai, Nullable<int> iDTTKN)
        {
            var iDKhieuNaiParameter = iDKhieuNai.HasValue ?
                new ObjectParameter("IDKhieuNai", iDKhieuNai) :
                new ObjectParameter("IDKhieuNai", typeof(int));
    
            var iDTTKNParameter = iDTTKN.HasValue ?
                new ObjectParameter("IDTTKN", iDTTKN) :
                new ObjectParameter("IDTTKN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_KhieuNai_updateTinhTrang", iDKhieuNaiParameter, iDTTKNParameter);
        }
    
        public virtual int DB_LinhVucHoatDong_delete(Nullable<int> iDLinhVucHĐ)
        {
            var iDLinhVucHĐParameter = iDLinhVucHĐ.HasValue ?
                new ObjectParameter("IDLinhVucHĐ", iDLinhVucHĐ) :
                new ObjectParameter("IDLinhVucHĐ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_LinhVucHoatDong_delete", iDLinhVucHĐParameter);
        }
    
        public virtual int DB_LinhVucHoatDong_insert(string tenLinhVucHĐ)
        {
            var tenLinhVucHĐParameter = tenLinhVucHĐ != null ?
                new ObjectParameter("TenLinhVucHĐ", tenLinhVucHĐ) :
                new ObjectParameter("TenLinhVucHĐ", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_LinhVucHoatDong_insert", tenLinhVucHĐParameter);
        }
    
        public virtual ObjectResult<DB_LinhVucHoatDong_searchByID_Result> DB_LinhVucHoatDong_searchByID(Nullable<int> iDLinhVucHĐ)
        {
            var iDLinhVucHĐParameter = iDLinhVucHĐ.HasValue ?
                new ObjectParameter("IDLinhVucHĐ", iDLinhVucHĐ) :
                new ObjectParameter("IDLinhVucHĐ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_LinhVucHoatDong_searchByID_Result>("DB_LinhVucHoatDong_searchByID", iDLinhVucHĐParameter);
        }
    
        public virtual int DB_LinhVucHoatDong_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_LinhVucHoatDong_select");
        }
    
        public virtual int DB_LinhVucHoatDong_update(Nullable<int> iDLinhVucHĐ, string tenLinhVucHĐ)
        {
            var iDLinhVucHĐParameter = iDLinhVucHĐ.HasValue ?
                new ObjectParameter("IDLinhVucHĐ", iDLinhVucHĐ) :
                new ObjectParameter("IDLinhVucHĐ", typeof(int));
    
            var tenLinhVucHĐParameter = tenLinhVucHĐ != null ?
                new ObjectParameter("TenLinhVucHĐ", tenLinhVucHĐ) :
                new ObjectParameter("TenLinhVucHĐ", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_LinhVucHoatDong_update", iDLinhVucHĐParameter, tenLinhVucHĐParameter);
        }
    
        public virtual int DB_LoaiDoiTac_delete(Nullable<int> iDLoaiDT)
        {
            var iDLoaiDTParameter = iDLoaiDT.HasValue ?
                new ObjectParameter("IDLoaiDT", iDLoaiDT) :
                new ObjectParameter("IDLoaiDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_LoaiDoiTac_delete", iDLoaiDTParameter);
        }
    
        public virtual int DB_LoaiDoiTac_insert(string tenLoaiDT)
        {
            var tenLoaiDTParameter = tenLoaiDT != null ?
                new ObjectParameter("TenLoaiDT", tenLoaiDT) :
                new ObjectParameter("TenLoaiDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_LoaiDoiTac_insert", tenLoaiDTParameter);
        }
    
        public virtual int DB_LoaiDoiTac_searchByID(Nullable<int> iDLoaiDT)
        {
            var iDLoaiDTParameter = iDLoaiDT.HasValue ?
                new ObjectParameter("IDLoaiDT", iDLoaiDT) :
                new ObjectParameter("IDLoaiDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_LoaiDoiTac_searchByID", iDLoaiDTParameter);
        }
    
        public virtual ObjectResult<DB_LoaiDoiTac_select_Result> DB_LoaiDoiTac_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_LoaiDoiTac_select_Result>("DB_LoaiDoiTac_select");
        }
    
        public virtual int DB_LoaiDoiTac_update(Nullable<int> iDLoaiDT, string tenLoaiDT)
        {
            var iDLoaiDTParameter = iDLoaiDT.HasValue ?
                new ObjectParameter("IDLoaiDT", iDLoaiDT) :
                new ObjectParameter("IDLoaiDT", typeof(int));
    
            var tenLoaiDTParameter = tenLoaiDT != null ?
                new ObjectParameter("TenLoaiDT", tenLoaiDT) :
                new ObjectParameter("TenLoaiDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_LoaiDoiTac_update", iDLoaiDTParameter, tenLoaiDTParameter);
        }
    
        public virtual int DB_Nhanvien_insert_API(string maNV, string hoTen, string hoTenKhongdau, string diaChi, string dienThoai, Nullable<System.DateTime> ngayVaolam, Nullable<int> iDPhongBan, Nullable<int> iDTinhTrangLV, Nullable<int> iDViTri)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var hoTenKhongdauParameter = hoTenKhongdau != null ?
                new ObjectParameter("HoTenKhongdau", hoTenKhongdau) :
                new ObjectParameter("HoTenKhongdau", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var ngayVaolamParameter = ngayVaolam.HasValue ?
                new ObjectParameter("NgayVaolam", ngayVaolam) :
                new ObjectParameter("NgayVaolam", typeof(System.DateTime));
    
            var iDPhongBanParameter = iDPhongBan.HasValue ?
                new ObjectParameter("IDPhongBan", iDPhongBan) :
                new ObjectParameter("IDPhongBan", typeof(int));
    
            var iDTinhTrangLVParameter = iDTinhTrangLV.HasValue ?
                new ObjectParameter("IDTinhTrangLV", iDTinhTrangLV) :
                new ObjectParameter("IDTinhTrangLV", typeof(int));
    
            var iDViTriParameter = iDViTri.HasValue ?
                new ObjectParameter("IDViTri", iDViTri) :
                new ObjectParameter("IDViTri", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Nhanvien_insert_API", maNVParameter, hoTenParameter, hoTenKhongdauParameter, diaChiParameter, dienThoaiParameter, ngayVaolamParameter, iDPhongBanParameter, iDTinhTrangLVParameter, iDViTriParameter);
        }
    
        public virtual int DB_Nhanvien_update_API(string maNV, string diaChi, string dienThoai, Nullable<int> iDPhongBan, Nullable<int> iDTinhTrangLV, Nullable<int> iDViTri)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var iDPhongBanParameter = iDPhongBan.HasValue ?
                new ObjectParameter("IDPhongBan", iDPhongBan) :
                new ObjectParameter("IDPhongBan", typeof(int));
    
            var iDTinhTrangLVParameter = iDTinhTrangLV.HasValue ?
                new ObjectParameter("IDTinhTrangLV", iDTinhTrangLV) :
                new ObjectParameter("IDTinhTrangLV", typeof(int));
    
            var iDViTriParameter = iDViTri.HasValue ?
                new ObjectParameter("IDViTri", iDViTri) :
                new ObjectParameter("IDViTri", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Nhanvien_update_API", maNVParameter, diaChiParameter, dienThoaiParameter, iDPhongBanParameter, iDTinhTrangLVParameter, iDViTriParameter);
        }
    
        public virtual int DB_PhanHoiDoiTac_delete(Nullable<int> iDPhanHoi)
        {
            var iDPhanHoiParameter = iDPhanHoi.HasValue ?
                new ObjectParameter("IDPhanHoi", iDPhanHoi) :
                new ObjectParameter("IDPhanHoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_PhanHoiDoiTac_delete", iDPhanHoiParameter);
        }
    
        public virtual int DB_PhanHoiDoiTac_insert(string maPhanHoi, string tieuDePH, string noiDungPH, string fileDinhKem, Nullable<System.DateTime> ngayPH, string iDNguoiPH, string tenNguoiPH, Nullable<int> khieuNaiID)
        {
            var maPhanHoiParameter = maPhanHoi != null ?
                new ObjectParameter("MaPhanHoi", maPhanHoi) :
                new ObjectParameter("MaPhanHoi", typeof(string));
    
            var tieuDePHParameter = tieuDePH != null ?
                new ObjectParameter("TieuDePH", tieuDePH) :
                new ObjectParameter("TieuDePH", typeof(string));
    
            var noiDungPHParameter = noiDungPH != null ?
                new ObjectParameter("NoiDungPH", noiDungPH) :
                new ObjectParameter("NoiDungPH", typeof(string));
    
            var fileDinhKemParameter = fileDinhKem != null ?
                new ObjectParameter("FileDinhKem", fileDinhKem) :
                new ObjectParameter("FileDinhKem", typeof(string));
    
            var ngayPHParameter = ngayPH.HasValue ?
                new ObjectParameter("NgayPH", ngayPH) :
                new ObjectParameter("NgayPH", typeof(System.DateTime));
    
            var iDNguoiPHParameter = iDNguoiPH != null ?
                new ObjectParameter("IDNguoiPH", iDNguoiPH) :
                new ObjectParameter("IDNguoiPH", typeof(string));
    
            var tenNguoiPHParameter = tenNguoiPH != null ?
                new ObjectParameter("TenNguoiPH", tenNguoiPH) :
                new ObjectParameter("TenNguoiPH", typeof(string));
    
            var khieuNaiIDParameter = khieuNaiID.HasValue ?
                new ObjectParameter("KhieuNaiID", khieuNaiID) :
                new ObjectParameter("KhieuNaiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_PhanHoiDoiTac_insert", maPhanHoiParameter, tieuDePHParameter, noiDungPHParameter, fileDinhKemParameter, ngayPHParameter, iDNguoiPHParameter, tenNguoiPHParameter, khieuNaiIDParameter);
        }
    
        public virtual ObjectResult<DB_PhanHoiDoiTac_searchByID_Result> DB_PhanHoiDoiTac_searchByID(Nullable<int> iDPhanHoi)
        {
            var iDPhanHoiParameter = iDPhanHoi.HasValue ?
                new ObjectParameter("IDPhanHoi", iDPhanHoi) :
                new ObjectParameter("IDPhanHoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_PhanHoiDoiTac_searchByID_Result>("DB_PhanHoiDoiTac_searchByID", iDPhanHoiParameter);
        }
    
        public virtual ObjectResult<DB_PhanHoiDoiTac_select_Result> DB_PhanHoiDoiTac_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_PhanHoiDoiTac_select_Result>("DB_PhanHoiDoiTac_select");
        }
    
        public virtual int DB_PhanHoiDoiTac_update(Nullable<int> iDPhanHoi, string maPhanHoi, string tieuDePH, string noiDungPH, string fileDinhKem, Nullable<System.DateTime> ngayPH, string iDNguoiPH, string tenNguoiPH, Nullable<int> khieuNaiID)
        {
            var iDPhanHoiParameter = iDPhanHoi.HasValue ?
                new ObjectParameter("IDPhanHoi", iDPhanHoi) :
                new ObjectParameter("IDPhanHoi", typeof(int));
    
            var maPhanHoiParameter = maPhanHoi != null ?
                new ObjectParameter("MaPhanHoi", maPhanHoi) :
                new ObjectParameter("MaPhanHoi", typeof(string));
    
            var tieuDePHParameter = tieuDePH != null ?
                new ObjectParameter("TieuDePH", tieuDePH) :
                new ObjectParameter("TieuDePH", typeof(string));
    
            var noiDungPHParameter = noiDungPH != null ?
                new ObjectParameter("NoiDungPH", noiDungPH) :
                new ObjectParameter("NoiDungPH", typeof(string));
    
            var fileDinhKemParameter = fileDinhKem != null ?
                new ObjectParameter("FileDinhKem", fileDinhKem) :
                new ObjectParameter("FileDinhKem", typeof(string));
    
            var ngayPHParameter = ngayPH.HasValue ?
                new ObjectParameter("NgayPH", ngayPH) :
                new ObjectParameter("NgayPH", typeof(System.DateTime));
    
            var iDNguoiPHParameter = iDNguoiPH != null ?
                new ObjectParameter("IDNguoiPH", iDNguoiPH) :
                new ObjectParameter("IDNguoiPH", typeof(string));
    
            var tenNguoiPHParameter = tenNguoiPH != null ?
                new ObjectParameter("TenNguoiPH", tenNguoiPH) :
                new ObjectParameter("TenNguoiPH", typeof(string));
    
            var khieuNaiIDParameter = khieuNaiID.HasValue ?
                new ObjectParameter("KhieuNaiID", khieuNaiID) :
                new ObjectParameter("KhieuNaiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_PhanHoiDoiTac_update", iDPhanHoiParameter, maPhanHoiParameter, tieuDePHParameter, noiDungPHParameter, fileDinhKemParameter, ngayPHParameter, iDNguoiPHParameter, tenNguoiPHParameter, khieuNaiIDParameter);
        }
    
        public virtual int DB_PhongBan_insert(ObjectParameter iDPhongBan, string tenPhongBan)
        {
            var tenPhongBanParameter = tenPhongBan != null ?
                new ObjectParameter("TenPhongBan", tenPhongBan) :
                new ObjectParameter("TenPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_PhongBan_insert", iDPhongBan, tenPhongBanParameter);
        }
    
        public virtual ObjectResult<DB_TaiKhoanDT_ID_Result> DB_TaiKhoanDT_ID(Nullable<int> iDDoitac)
        {
            var iDDoitacParameter = iDDoitac.HasValue ?
                new ObjectParameter("IDDoitac", iDDoitac) :
                new ObjectParameter("IDDoitac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_TaiKhoanDT_ID_Result>("DB_TaiKhoanDT_ID", iDDoitacParameter);
        }
    
        public virtual ObjectResult<DB_TaiKhoanDT_select_Result> DB_TaiKhoanDT_select(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_TaiKhoanDT_select_Result>("DB_TaiKhoanDT_select", searchParameter);
        }
    
        public virtual int DB_TaiKhoanDT_Update(Nullable<int> iDDoiTac, string matKhau)
        {
            var iDDoiTacParameter = iDDoiTac.HasValue ?
                new ObjectParameter("IDDoiTac", iDDoiTac) :
                new ObjectParameter("IDDoiTac", typeof(int));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TaiKhoanDT_Update", iDDoiTacParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<DB_TaiKhoanNV_ID_Result> DB_TaiKhoanNV_ID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_TaiKhoanNV_ID_Result>("DB_TaiKhoanNV_ID", iDParameter);
        }
    
        public virtual ObjectResult<DB_TaiKhoanNV_select_Result> DB_TaiKhoanNV_select(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_TaiKhoanNV_select_Result>("DB_TaiKhoanNV_select", searchParameter);
        }
    
        public virtual int DB_TaiKhoanNV_Update(Nullable<int> iD, string matKhau)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TaiKhoanNV_Update", iDParameter, matKhauParameter);
        }
    
        public virtual int DB_ThongBao_delete(Nullable<int> iDTBao)
        {
            var iDTBaoParameter = iDTBao.HasValue ?
                new ObjectParameter("IDTBao", iDTBao) :
                new ObjectParameter("IDTBao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_ThongBao_delete", iDTBaoParameter);
        }
    
        public virtual int DB_ThongBao_insert(string maTBao, string noiDungTBao, string fileDinhKem, Nullable<System.DateTime> ngay, Nullable<int> tinhTrangTB)
        {
            var maTBaoParameter = maTBao != null ?
                new ObjectParameter("MaTBao", maTBao) :
                new ObjectParameter("MaTBao", typeof(string));
    
            var noiDungTBaoParameter = noiDungTBao != null ?
                new ObjectParameter("NoiDungTBao", noiDungTBao) :
                new ObjectParameter("NoiDungTBao", typeof(string));
    
            var fileDinhKemParameter = fileDinhKem != null ?
                new ObjectParameter("FileDinhKem", fileDinhKem) :
                new ObjectParameter("FileDinhKem", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(System.DateTime));
    
            var tinhTrangTBParameter = tinhTrangTB.HasValue ?
                new ObjectParameter("TinhTrangTB", tinhTrangTB) :
                new ObjectParameter("TinhTrangTB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_ThongBao_insert", maTBaoParameter, noiDungTBaoParameter, fileDinhKemParameter, ngayParameter, tinhTrangTBParameter);
        }
    
        public virtual ObjectResult<DB_ThongBao_searchByID_Result> DB_ThongBao_searchByID(Nullable<int> iDTBao)
        {
            var iDTBaoParameter = iDTBao.HasValue ?
                new ObjectParameter("IDTBao", iDTBao) :
                new ObjectParameter("IDTBao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_ThongBao_searchByID_Result>("DB_ThongBao_searchByID", iDTBaoParameter);
        }
    
        public virtual ObjectResult<DB_ThongBao_select_Result> DB_ThongBao_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_ThongBao_select_Result>("DB_ThongBao_select");
        }
    
        public virtual int DB_ThongBao_update(Nullable<int> iDTBao, string maTBao, string noiDungTBao, string fileDinhKem, Nullable<System.DateTime> ngay, Nullable<int> tinhTrangTB)
        {
            var iDTBaoParameter = iDTBao.HasValue ?
                new ObjectParameter("IDTBao", iDTBao) :
                new ObjectParameter("IDTBao", typeof(int));
    
            var maTBaoParameter = maTBao != null ?
                new ObjectParameter("MaTBao", maTBao) :
                new ObjectParameter("MaTBao", typeof(string));
    
            var noiDungTBaoParameter = noiDungTBao != null ?
                new ObjectParameter("NoiDungTBao", noiDungTBao) :
                new ObjectParameter("NoiDungTBao", typeof(string));
    
            var fileDinhKemParameter = fileDinhKem != null ?
                new ObjectParameter("FileDinhKem", fileDinhKem) :
                new ObjectParameter("FileDinhKem", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(System.DateTime));
    
            var tinhTrangTBParameter = tinhTrangTB.HasValue ?
                new ObjectParameter("TinhTrangTB", tinhTrangTB) :
                new ObjectParameter("TinhTrangTB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_ThongBao_update", iDTBaoParameter, maTBaoParameter, noiDungTBaoParameter, fileDinhKemParameter, ngayParameter, tinhTrangTBParameter);
        }
    
        public virtual int DB_ThongBaoDoiTac_delete(Nullable<int> iD_TBDT)
        {
            var iD_TBDTParameter = iD_TBDT.HasValue ?
                new ObjectParameter("ID_TBDT", iD_TBDT) :
                new ObjectParameter("ID_TBDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_ThongBaoDoiTac_delete", iD_TBDTParameter);
        }
    
        public virtual int DB_ThongBaoDoiTac_insert(Nullable<int> tBID, Nullable<int> doiTacID)
        {
            var tBIDParameter = tBID.HasValue ?
                new ObjectParameter("TBID", tBID) :
                new ObjectParameter("TBID", typeof(int));
    
            var doiTacIDParameter = doiTacID.HasValue ?
                new ObjectParameter("DoiTacID", doiTacID) :
                new ObjectParameter("DoiTacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_ThongBaoDoiTac_insert", tBIDParameter, doiTacIDParameter);
        }
    
        public virtual ObjectResult<DB_ThongBaoDoiTac_searchByID_Result> DB_ThongBaoDoiTac_searchByID(Nullable<int> iD_TBDT)
        {
            var iD_TBDTParameter = iD_TBDT.HasValue ?
                new ObjectParameter("ID_TBDT", iD_TBDT) :
                new ObjectParameter("ID_TBDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_ThongBaoDoiTac_searchByID_Result>("DB_ThongBaoDoiTac_searchByID", iD_TBDTParameter);
        }
    
        public virtual ObjectResult<DB_ThongBaoDoiTac_select_Result> DB_ThongBaoDoiTac_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_ThongBaoDoiTac_select_Result>("DB_ThongBaoDoiTac_select");
        }
    
        public virtual int DB_ThongBaoDoiTac_update(Nullable<int> iD_TBDT, Nullable<int> tBID, Nullable<int> doiTacID)
        {
            var iD_TBDTParameter = iD_TBDT.HasValue ?
                new ObjectParameter("ID_TBDT", iD_TBDT) :
                new ObjectParameter("ID_TBDT", typeof(int));
    
            var tBIDParameter = tBID.HasValue ?
                new ObjectParameter("TBID", tBID) :
                new ObjectParameter("TBID", typeof(int));
    
            var doiTacIDParameter = doiTacID.HasValue ?
                new ObjectParameter("DoiTacID", doiTacID) :
                new ObjectParameter("DoiTacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_ThongBaoDoiTac_update", iD_TBDTParameter, tBIDParameter, doiTacIDParameter);
        }
    
        public virtual ObjectResult<DB_TinTrangKhieuNai_searchByID_Result> DB_TinTrangKhieuNai_searchByID(Nullable<int> iDTTKN)
        {
            var iDTTKNParameter = iDTTKN.HasValue ?
                new ObjectParameter("IDTTKN", iDTTKN) :
                new ObjectParameter("IDTTKN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_TinTrangKhieuNai_searchByID_Result>("DB_TinTrangKhieuNai_searchByID", iDTTKNParameter);
        }
    
        public virtual int DB_TinTuc_delete(Nullable<int> iDTinTuc)
        {
            var iDTinTucParameter = iDTinTuc.HasValue ?
                new ObjectParameter("IDTinTuc", iDTinTuc) :
                new ObjectParameter("IDTinTuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TinTuc_delete", iDTinTucParameter);
        }
    
        public virtual int DB_TinTuc_insert(string tenDeTai, string tomTatTinTuc, string noiDungTinTuc, string imageTinTuc, string nguoiDangTin)
        {
            var tenDeTaiParameter = tenDeTai != null ?
                new ObjectParameter("TenDeTai", tenDeTai) :
                new ObjectParameter("TenDeTai", typeof(string));
    
            var tomTatTinTucParameter = tomTatTinTuc != null ?
                new ObjectParameter("TomTatTinTuc", tomTatTinTuc) :
                new ObjectParameter("TomTatTinTuc", typeof(string));
    
            var noiDungTinTucParameter = noiDungTinTuc != null ?
                new ObjectParameter("NoiDungTinTuc", noiDungTinTuc) :
                new ObjectParameter("NoiDungTinTuc", typeof(string));
    
            var imageTinTucParameter = imageTinTuc != null ?
                new ObjectParameter("ImageTinTuc", imageTinTuc) :
                new ObjectParameter("ImageTinTuc", typeof(string));
    
            var nguoiDangTinParameter = nguoiDangTin != null ?
                new ObjectParameter("NguoiDangTin", nguoiDangTin) :
                new ObjectParameter("NguoiDangTin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TinTuc_insert", tenDeTaiParameter, tomTatTinTucParameter, noiDungTinTucParameter, imageTinTucParameter, nguoiDangTinParameter);
        }
    
        public virtual ObjectResult<DB_TinTuc_searchByID_Result> DB_TinTuc_searchByID(Nullable<int> iDTinTuc)
        {
            var iDTinTucParameter = iDTinTuc.HasValue ?
                new ObjectParameter("IDTinTuc", iDTinTuc) :
                new ObjectParameter("IDTinTuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_TinTuc_searchByID_Result>("DB_TinTuc_searchByID", iDTinTucParameter);
        }
    
        public virtual ObjectResult<DB_TinTuc_select_Result> DB_TinTuc_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_TinTuc_select_Result>("DB_TinTuc_select");
        }
    
        public virtual int DB_TinTuc_update(Nullable<int> iDTinTuc, string tenDeTai, string tomTatTinTuc, string noiDungTinTuc, string imageTinTuc, string nguoiDangTin)
        {
            var iDTinTucParameter = iDTinTuc.HasValue ?
                new ObjectParameter("IDTinTuc", iDTinTuc) :
                new ObjectParameter("IDTinTuc", typeof(int));
    
            var tenDeTaiParameter = tenDeTai != null ?
                new ObjectParameter("TenDeTai", tenDeTai) :
                new ObjectParameter("TenDeTai", typeof(string));
    
            var tomTatTinTucParameter = tomTatTinTuc != null ?
                new ObjectParameter("TomTatTinTuc", tomTatTinTuc) :
                new ObjectParameter("TomTatTinTuc", typeof(string));
    
            var noiDungTinTucParameter = noiDungTinTuc != null ?
                new ObjectParameter("NoiDungTinTuc", noiDungTinTuc) :
                new ObjectParameter("NoiDungTinTuc", typeof(string));
    
            var imageTinTucParameter = imageTinTuc != null ?
                new ObjectParameter("ImageTinTuc", imageTinTuc) :
                new ObjectParameter("ImageTinTuc", typeof(string));
    
            var nguoiDangTinParameter = nguoiDangTin != null ?
                new ObjectParameter("NguoiDangTin", nguoiDangTin) :
                new ObjectParameter("NguoiDangTin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TinTuc_update", iDTinTucParameter, tenDeTaiParameter, tomTatTinTucParameter, noiDungTinTucParameter, imageTinTucParameter, nguoiDangTinParameter);
        }
    
        public virtual int DB_TKDT_Update_Quyen(Nullable<int> iDDoiTac, Nullable<int> iDQuyen)
        {
            var iDDoiTacParameter = iDDoiTac.HasValue ?
                new ObjectParameter("IDDoiTac", iDDoiTac) :
                new ObjectParameter("IDDoiTac", typeof(int));
    
            var iDQuyenParameter = iDQuyen.HasValue ?
                new ObjectParameter("IDQuyen", iDQuyen) :
                new ObjectParameter("IDQuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TKDT_Update_Quyen", iDDoiTacParameter, iDQuyenParameter);
        }
    
        public virtual int DB_TKNV_Update_Quyen(Nullable<int> iD, Nullable<int> iDQuyen)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iDQuyenParameter = iDQuyen.HasValue ?
                new ObjectParameter("IDQuyen", iDQuyen) :
                new ObjectParameter("IDQuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TKNV_Update_Quyen", iDParameter, iDQuyenParameter);
        }
    
        public virtual int DB_TTDoiTac_delete(Nullable<int> iDDoiTac)
        {
            var iDDoiTacParameter = iDDoiTac.HasValue ?
                new ObjectParameter("IDDoiTac", iDDoiTac) :
                new ObjectParameter("IDDoiTac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TTDoiTac_delete", iDDoiTacParameter);
        }
    
        public virtual int DB_TTDoiTac_insert(string bPID, string fullName, string shortName, string taxcode, string address, Nullable<int> city, Nullable<int> regions, string imageLogo, string customer, string vender, string email, string linhVucHD, string loaiIDDT)
        {
            var bPIDParameter = bPID != null ?
                new ObjectParameter("BPID", bPID) :
                new ObjectParameter("BPID", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var shortNameParameter = shortName != null ?
                new ObjectParameter("ShortName", shortName) :
                new ObjectParameter("ShortName", typeof(string));
    
            var taxcodeParameter = taxcode != null ?
                new ObjectParameter("Taxcode", taxcode) :
                new ObjectParameter("Taxcode", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var cityParameter = city.HasValue ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(int));
    
            var regionsParameter = regions.HasValue ?
                new ObjectParameter("Regions", regions) :
                new ObjectParameter("Regions", typeof(int));
    
            var imageLogoParameter = imageLogo != null ?
                new ObjectParameter("ImageLogo", imageLogo) :
                new ObjectParameter("ImageLogo", typeof(string));
    
            var customerParameter = customer != null ?
                new ObjectParameter("Customer", customer) :
                new ObjectParameter("Customer", typeof(string));
    
            var venderParameter = vender != null ?
                new ObjectParameter("Vender", vender) :
                new ObjectParameter("Vender", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var linhVucHDParameter = linhVucHD != null ?
                new ObjectParameter("LinhVucHD", linhVucHD) :
                new ObjectParameter("LinhVucHD", typeof(string));
    
            var loaiIDDTParameter = loaiIDDT != null ?
                new ObjectParameter("LoaiIDDT", loaiIDDT) :
                new ObjectParameter("LoaiIDDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TTDoiTac_insert", bPIDParameter, fullNameParameter, shortNameParameter, taxcodeParameter, addressParameter, cityParameter, regionsParameter, imageLogoParameter, customerParameter, venderParameter, emailParameter, linhVucHDParameter, loaiIDDTParameter);
        }
    
        public virtual ObjectResult<DB_TTDoiTac_searchByID_Result> DB_TTDoiTac_searchByID(Nullable<int> iDDoiTac)
        {
            var iDDoiTacParameter = iDDoiTac.HasValue ?
                new ObjectParameter("IDDoiTac", iDDoiTac) :
                new ObjectParameter("IDDoiTac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_TTDoiTac_searchByID_Result>("DB_TTDoiTac_searchByID", iDDoiTacParameter);
        }
    
        public virtual ObjectResult<DB_TTDoiTac_select_Result> DB_TTDoiTac_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DB_TTDoiTac_select_Result>("DB_TTDoiTac_select");
        }
    
        public virtual int DB_TTDoiTac_update(Nullable<int> iDDoiTac, string bPID, string fullName, string shortName, string taxCode, string address, Nullable<int> city, Nullable<int> regions, string imageLogo, string customer, string vender, string email, string linhVucHD, string loaiIDDT)
        {
            var iDDoiTacParameter = iDDoiTac.HasValue ?
                new ObjectParameter("IDDoiTac", iDDoiTac) :
                new ObjectParameter("IDDoiTac", typeof(int));
    
            var bPIDParameter = bPID != null ?
                new ObjectParameter("BPID", bPID) :
                new ObjectParameter("BPID", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var shortNameParameter = shortName != null ?
                new ObjectParameter("ShortName", shortName) :
                new ObjectParameter("ShortName", typeof(string));
    
            var taxCodeParameter = taxCode != null ?
                new ObjectParameter("TaxCode", taxCode) :
                new ObjectParameter("TaxCode", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var cityParameter = city.HasValue ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(int));
    
            var regionsParameter = regions.HasValue ?
                new ObjectParameter("Regions", regions) :
                new ObjectParameter("Regions", typeof(int));
    
            var imageLogoParameter = imageLogo != null ?
                new ObjectParameter("ImageLogo", imageLogo) :
                new ObjectParameter("ImageLogo", typeof(string));
    
            var customerParameter = customer != null ?
                new ObjectParameter("Customer", customer) :
                new ObjectParameter("Customer", typeof(string));
    
            var venderParameter = vender != null ?
                new ObjectParameter("Vender", vender) :
                new ObjectParameter("Vender", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var linhVucHDParameter = linhVucHD != null ?
                new ObjectParameter("LinhVucHD", linhVucHD) :
                new ObjectParameter("LinhVucHD", typeof(string));
    
            var loaiIDDTParameter = loaiIDDT != null ?
                new ObjectParameter("LoaiIDDT", loaiIDDT) :
                new ObjectParameter("LoaiIDDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TTDoiTac_update", iDDoiTacParameter, bPIDParameter, fullNameParameter, shortNameParameter, taxCodeParameter, addressParameter, cityParameter, regionsParameter, imageLogoParameter, customerParameter, venderParameter, emailParameter, linhVucHDParameter, loaiIDDTParameter);
        }
    
        public virtual int DB_Vitri_insert(ObjectParameter iDVitri, string tenVitri)
        {
            var tenVitriParameter = tenVitri != null ?
                new ObjectParameter("TenVitri", tenVitri) :
                new ObjectParameter("TenVitri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Vitri_insert", iDVitri, tenVitriParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int DB_Benefit_delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Benefit_delete", iDParameter);
        }
    
        public virtual int DB_Benefit_insert(string tieuDe, string noiDung, string hinhAnh)
        {
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Benefit_insert", tieuDeParameter, noiDungParameter, hinhAnhParameter);
        }
    
        public virtual int DB_Benefit_update(Nullable<int> iD, string tieuDe, string noiDung, string hinhAnh)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Benefit_update", iDParameter, tieuDeParameter, noiDungParameter, hinhAnhParameter);
        }
    
        public virtual int DB_IntroductTD_delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_IntroductTD_delete", iDParameter);
        }
    
        public virtual int DB_IntroductTD_insert(string tieuDe, string noiDung, string hinhAnh, string note1, string note2)
        {
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var note1Parameter = note1 != null ?
                new ObjectParameter("Note1", note1) :
                new ObjectParameter("Note1", typeof(string));
    
            var note2Parameter = note2 != null ?
                new ObjectParameter("Note2", note2) :
                new ObjectParameter("Note2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_IntroductTD_insert", tieuDeParameter, noiDungParameter, hinhAnhParameter, note1Parameter, note2Parameter);
        }
    
        public virtual int DB_IntroductTD_update(Nullable<int> iD, string tieuDe, string noiDung, string hinhAnh, string note1, string note2)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var note1Parameter = note1 != null ?
                new ObjectParameter("Note1", note1) :
                new ObjectParameter("Note1", typeof(string));
    
            var note2Parameter = note2 != null ?
                new ObjectParameter("Note2", note2) :
                new ObjectParameter("Note2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_IntroductTD_update", iDParameter, tieuDeParameter, noiDungParameter, hinhAnhParameter, note1Parameter, note2Parameter);
        }
    
        public virtual int DB_Mission_delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Mission_delete", iDParameter);
        }
    
        public virtual int DB_Mission_insert(string tieuDe, string noiDung)
        {
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Mission_insert", tieuDeParameter, noiDungParameter);
        }
    
        public virtual int DB_Mission_update(Nullable<int> iD, string tieuDe, string noiDung)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Mission_update", iDParameter, tieuDeParameter, noiDungParameter);
        }
    
        public virtual int DB_Picture_delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Picture_delete", iDParameter);
        }
    
        public virtual int DB_Picture_insert(string tenHinhAnh, string image)
        {
            var tenHinhAnhParameter = tenHinhAnh != null ?
                new ObjectParameter("TenHinhAnh", tenHinhAnh) :
                new ObjectParameter("TenHinhAnh", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Picture_insert", tenHinhAnhParameter, imageParameter);
        }
    
        public virtual int DB_Picture_update(Nullable<int> iD, string tenHinhAnh, string image)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tenHinhAnhParameter = tenHinhAnh != null ?
                new ObjectParameter("TenHinhAnh", tenHinhAnh) :
                new ObjectParameter("TenHinhAnh", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_Picture_update", iDParameter, tenHinhAnhParameter, imageParameter);
        }
    
        public virtual int DB_TongQuan_delete(Nullable<int> iDTQ)
        {
            var iDTQParameter = iDTQ.HasValue ?
                new ObjectParameter("IDTQ", iDTQ) :
                new ObjectParameter("IDTQ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TongQuan_delete", iDTQParameter);
        }
    
        public virtual int DB_TongQuan_insert(string tieuDe, string tomTat, string dayDu, string note, string image)
        {
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var tomTatParameter = tomTat != null ?
                new ObjectParameter("TomTat", tomTat) :
                new ObjectParameter("TomTat", typeof(string));
    
            var dayDuParameter = dayDu != null ?
                new ObjectParameter("DayDu", dayDu) :
                new ObjectParameter("DayDu", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TongQuan_insert", tieuDeParameter, tomTatParameter, dayDuParameter, noteParameter, imageParameter);
        }
    
        public virtual int DB_TongQuan_update(Nullable<int> iDTQ, string tieuDe, string tomTat, string dayDu, string note, string image)
        {
            var iDTQParameter = iDTQ.HasValue ?
                new ObjectParameter("IDTQ", iDTQ) :
                new ObjectParameter("IDTQ", typeof(int));
    
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var tomTatParameter = tomTat != null ?
                new ObjectParameter("TomTat", tomTat) :
                new ObjectParameter("TomTat", typeof(string));
    
            var dayDuParameter = dayDu != null ?
                new ObjectParameter("DayDu", dayDu) :
                new ObjectParameter("DayDu", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DB_TongQuan_update", iDTQParameter, tieuDeParameter, tomTatParameter, dayDuParameter, noteParameter, imageParameter);
        }
    }
}
