//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsDanhBaDoiTac
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_HangMuc
    {
        public int IDHangMuc { get; set; }
        public string MaHM { get; set; }
        public string TenHangMuc { get; set; }
        public Nullable<System.DateTime> NgayKyHĐ { get; set; }
        public Nullable<int> LinhVucHM_ID { get; set; }
        public Nullable<int> DoiTacID { get; set; }
    
        public virtual DB_LinhVucNB DB_LinhVucNB { get; set; }
        public virtual DB_TTDoiTac DB_TTDoiTac { get; set; }
    }
}
