//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsDanhBaDoiTac
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_NhanVien
    {
        public int ID { get; set; }
        public string MaNV { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string HoTenKhongDau { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public Nullable<int> IDTinhTrangLV { get; set; }
        public Nullable<int> IDViTri { get; set; }
        public Nullable<int> IDQuyen { get; set; }
        public Nullable<int> isDB { get; set; }
        public Nullable<int> isDoiTac { get; set; }
    }
}
