//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsDanhBaDoiTac
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_PhanHoiDoiTac
    {
        public int IDPhanHoi { get; set; }
        public string MaPhanHoi { get; set; }
        public string TieuDePH { get; set; }
        public string NoiDungPH { get; set; }
        public string FileDinhKem { get; set; }
        public Nullable<System.DateTime> NgayPH { get; set; }
        public string IDNguoiPH { get; set; }
        public string TenNguoiPH { get; set; }
        public int KhieuNaiID { get; set; }
    
        public virtual DB_KhieuNai DB_KhieuNai { get; set; }
    }
}
