//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsDanhBaDoiTac
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_TongQuan
    {
        public int IDTQ { get; set; }
        public string TieuDe { get; set; }
        public string TomTat { get; set; }
        public string DayDu { get; set; }
        public string Note { get; set; }
        public string Image { get; set; }
    }
}
