//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsDanhBaDoiTac
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_ThongBao_DoiTac
    {
        public int ID_TBDT { get; set; }
        public Nullable<int> TBID { get; set; }
        public Nullable<int> DoiTacID { get; set; }
    
        public virtual DB_ThongBao DB_ThongBao { get; set; }
        public virtual DB_TTDoiTac DB_TTDoiTac { get; set; }
    }
}
