//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsDanhBaDoiTac
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_ThongBao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DB_ThongBao()
        {
            this.DB_ThongBao_DoiTac = new HashSet<DB_ThongBao_DoiTac>();
        }
    
        public int IDTBao { get; set; }
        public string MaTBao { get; set; }
        public string NoiDungTBao { get; set; }
        public string FileDinhKem { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> TinhTrangTB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DB_ThongBao_DoiTac> DB_ThongBao_DoiTac { get; set; }
        public virtual DB_TinhTrangThongBao DB_TinhTrangThongBao { get; set; }
    }
}
