//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsDanhBaDoiTac
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_TTDoiTac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DB_TTDoiTac()
        {
            this.DB_HangMuc = new HashSet<DB_HangMuc>();
            this.DB_KhieuNai = new HashSet<DB_KhieuNai>();
            this.DB_ThongBao_DoiTac = new HashSet<DB_ThongBao_DoiTac>();
        }
    
        public int IDDoiTac { get; set; }
        public string BPID { get; set; }
        public string MatKhau { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string Taxcode { get; set; }
        public string Address { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Regions { get; set; }
        public string ImageLogo { get; set; }
        public string Customer { get; set; }
        public string Vender { get; set; }
        public string Email { get; set; }
        public string LinhVucHĐ { get; set; }
        public string LoaiIDDT { get; set; }
        public string CodeUnis { get; set; }
        public Nullable<int> IDQuyen { get; set; }
        public Nullable<int> isDT { get; set; }
    
        public virtual DB_DiaChi DB_DiaChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DB_HangMuc> DB_HangMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DB_KhieuNai> DB_KhieuNai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DB_ThongBao_DoiTac> DB_ThongBao_DoiTac { get; set; }
    }
}
