

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsPartner
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class EPORTAL_NTEntities : DbContext
{
    public EPORTAL_NTEntities()
        : base("name=EPORTAL_NTEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<LoaiPT> LoaiPTs { get; set; }

    public virtual DbSet<NT_CardMobility> NT_CardMobility { get; set; }

    public virtual DbSet<NT_CardTemp> NT_CardTemp { get; set; }

    public virtual DbSet<NT_CarteTemp> NT_CarteTemp { get; set; }

    public virtual DbSet<NT_CarteTemporaire> NT_CarteTemporaire { get; set; }

    public virtual DbSet<NT_ContactEquipment> NT_ContactEquipment { get; set; }

    public virtual DbSet<NT_DetailCarteTemporaire> NT_DetailCarteTemporaire { get; set; }

    public virtual DbSet<NT_Handle> NT_Handle { get; set; }

    public virtual DbSet<NT_HistoryBlackList> NT_HistoryBlackList { get; set; }

    public virtual DbSet<NT_HoatDongNV> NT_HoatDongNV { get; set; }

    public virtual DbSet<NT_NhanVienNT> NT_NhanVienNT { get; set; }

    public virtual DbSet<NT_NhanVienVP> NT_NhanVienVP { get; set; }

    public virtual DbSet<NT_Purpose> NT_Purpose { get; set; }

    public virtual DbSet<NT_TTHD> NT_TTHD { get; set; }

    public virtual DbSet<NT_UserTemp> NT_UserTemp { get; set; }

    public virtual DbSet<NT_MaDinhDanh> NT_MaDinhDanh { get; set; }


    public virtual int NT_CardMobility_delete(Nullable<int> iDCD)
    {

        var iDCDParameter = iDCD.HasValue ?
            new ObjectParameter("IDCD", iDCD) :
            new ObjectParameter("IDCD", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_CardMobility_delete", iDCDParameter);
    }


    public virtual int NT_CardMobility_insert(Nullable<int> iDNVNT, Nullable<int> iDNT, string loaiPT, string hangxe, string dongxe, string mausac, string bienso, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string sothe, Nullable<int> iDTT)
    {

        var iDNVNTParameter = iDNVNT.HasValue ?
            new ObjectParameter("IDNVNT", iDNVNT) :
            new ObjectParameter("IDNVNT", typeof(int));


        var iDNTParameter = iDNT.HasValue ?
            new ObjectParameter("IDNT", iDNT) :
            new ObjectParameter("IDNT", typeof(int));


        var loaiPTParameter = loaiPT != null ?
            new ObjectParameter("LoaiPT", loaiPT) :
            new ObjectParameter("LoaiPT", typeof(string));


        var hangxeParameter = hangxe != null ?
            new ObjectParameter("Hangxe", hangxe) :
            new ObjectParameter("Hangxe", typeof(string));


        var dongxeParameter = dongxe != null ?
            new ObjectParameter("Dongxe", dongxe) :
            new ObjectParameter("Dongxe", typeof(string));


        var mausacParameter = mausac != null ?
            new ObjectParameter("Mausac", mausac) :
            new ObjectParameter("Mausac", typeof(string));


        var biensoParameter = bienso != null ?
            new ObjectParameter("Bienso", bienso) :
            new ObjectParameter("Bienso", typeof(string));


        var tungayParameter = tungay.HasValue ?
            new ObjectParameter("Tungay", tungay) :
            new ObjectParameter("Tungay", typeof(System.DateTime));


        var denngayParameter = denngay.HasValue ?
            new ObjectParameter("Denngay", denngay) :
            new ObjectParameter("Denngay", typeof(System.DateTime));


        var sotheParameter = sothe != null ?
            new ObjectParameter("Sothe", sothe) :
            new ObjectParameter("Sothe", typeof(string));


        var iDTTParameter = iDTT.HasValue ?
            new ObjectParameter("IDTT", iDTT) :
            new ObjectParameter("IDTT", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_CardMobility_insert", iDNVNTParameter, iDNTParameter, loaiPTParameter, hangxeParameter, dongxeParameter, mausacParameter, biensoParameter, tungayParameter, denngayParameter, sotheParameter, iDTTParameter);
    }


    public virtual ObjectResult<NT_CardMobility_Select_Result> NT_CardMobility_Select(string search)
    {

        var searchParameter = search != null ?
            new ObjectParameter("search", search) :
            new ObjectParameter("search", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NT_CardMobility_Select_Result>("NT_CardMobility_Select", searchParameter);
    }


    public virtual int NT_CardMobility_update(Nullable<int> iDCD, Nullable<int> iDNVNT, Nullable<int> iDNT, string loaiPT, string hangxe, string dongxe, string mausac, string bienso, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string sothe, Nullable<int> iDTT)
    {

        var iDCDParameter = iDCD.HasValue ?
            new ObjectParameter("IDCD", iDCD) :
            new ObjectParameter("IDCD", typeof(int));


        var iDNVNTParameter = iDNVNT.HasValue ?
            new ObjectParameter("IDNVNT", iDNVNT) :
            new ObjectParameter("IDNVNT", typeof(int));


        var iDNTParameter = iDNT.HasValue ?
            new ObjectParameter("IDNT", iDNT) :
            new ObjectParameter("IDNT", typeof(int));


        var loaiPTParameter = loaiPT != null ?
            new ObjectParameter("LoaiPT", loaiPT) :
            new ObjectParameter("LoaiPT", typeof(string));


        var hangxeParameter = hangxe != null ?
            new ObjectParameter("Hangxe", hangxe) :
            new ObjectParameter("Hangxe", typeof(string));


        var dongxeParameter = dongxe != null ?
            new ObjectParameter("Dongxe", dongxe) :
            new ObjectParameter("Dongxe", typeof(string));


        var mausacParameter = mausac != null ?
            new ObjectParameter("Mausac", mausac) :
            new ObjectParameter("Mausac", typeof(string));


        var biensoParameter = bienso != null ?
            new ObjectParameter("Bienso", bienso) :
            new ObjectParameter("Bienso", typeof(string));


        var tungayParameter = tungay.HasValue ?
            new ObjectParameter("Tungay", tungay) :
            new ObjectParameter("Tungay", typeof(System.DateTime));


        var denngayParameter = denngay.HasValue ?
            new ObjectParameter("Denngay", denngay) :
            new ObjectParameter("Denngay", typeof(System.DateTime));


        var sotheParameter = sothe != null ?
            new ObjectParameter("Sothe", sothe) :
            new ObjectParameter("Sothe", typeof(string));


        var iDTTParameter = iDTT.HasValue ?
            new ObjectParameter("IDTT", iDTT) :
            new ObjectParameter("IDTT", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_CardMobility_update", iDCDParameter, iDNVNTParameter, iDNTParameter, loaiPTParameter, hangxeParameter, dongxeParameter, mausacParameter, biensoParameter, tungayParameter, denngayParameter, sotheParameter, iDTTParameter);
    }


    public virtual int NT_CardTemp_delete(Nullable<int> iDThe)
    {

        var iDTheParameter = iDThe.HasValue ?
            new ObjectParameter("IDThe", iDThe) :
            new ObjectParameter("IDThe", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_CardTemp_delete", iDTheParameter);
    }


    public virtual int NT_CardTemp_insert(string maThe, string tenThe, string userID, string employeeID, Nullable<int> iDCong)
    {

        var maTheParameter = maThe != null ?
            new ObjectParameter("MaThe", maThe) :
            new ObjectParameter("MaThe", typeof(string));


        var tenTheParameter = tenThe != null ?
            new ObjectParameter("TenThe", tenThe) :
            new ObjectParameter("TenThe", typeof(string));


        var userIDParameter = userID != null ?
            new ObjectParameter("UserID", userID) :
            new ObjectParameter("UserID", typeof(string));


        var employeeIDParameter = employeeID != null ?
            new ObjectParameter("EmployeeID", employeeID) :
            new ObjectParameter("EmployeeID", typeof(string));


        var iDCongParameter = iDCong.HasValue ?
            new ObjectParameter("IDCong", iDCong) :
            new ObjectParameter("IDCong", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_CardTemp_insert", maTheParameter, tenTheParameter, userIDParameter, employeeIDParameter, iDCongParameter);
    }


    public virtual int NT_CardTemp_update(Nullable<int> iDThe, string maThe, string tenThe, string userID, string employeeID, Nullable<int> iDCong)
    {

        var iDTheParameter = iDThe.HasValue ?
            new ObjectParameter("IDThe", iDThe) :
            new ObjectParameter("IDThe", typeof(int));


        var maTheParameter = maThe != null ?
            new ObjectParameter("MaThe", maThe) :
            new ObjectParameter("MaThe", typeof(string));


        var tenTheParameter = tenThe != null ?
            new ObjectParameter("TenThe", tenThe) :
            new ObjectParameter("TenThe", typeof(string));


        var userIDParameter = userID != null ?
            new ObjectParameter("UserID", userID) :
            new ObjectParameter("UserID", typeof(string));


        var employeeIDParameter = employeeID != null ?
            new ObjectParameter("EmployeeID", employeeID) :
            new ObjectParameter("EmployeeID", typeof(string));


        var iDCongParameter = iDCong.HasValue ?
            new ObjectParameter("IDCong", iDCong) :
            new ObjectParameter("IDCong", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_CardTemp_update", iDTheParameter, maTheParameter, tenTheParameter, userIDParameter, employeeIDParameter, iDCongParameter);
    }


    public virtual int NT_CarteTemporaire_Cancel(Nullable<int> iDTTT, Nullable<int> tinhTrang, string ghiChu)
    {

        var iDTTTParameter = iDTTT.HasValue ?
            new ObjectParameter("IDTTT", iDTTT) :
            new ObjectParameter("IDTTT", typeof(int));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_CarteTemporaire_Cancel", iDTTTParameter, tinhTrangParameter, ghiChuParameter);
    }


    public virtual int NT_CarteTemporaire_delete(Nullable<int> iDTTT)
    {

        var iDTTTParameter = iDTTT.HasValue ?
            new ObjectParameter("IDTTT", iDTTT) :
            new ObjectParameter("IDTTT", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_CarteTemporaire_delete", iDTTTParameter);
    }


    public virtual int NT_CarteTemporaire_insert(string noiDung, Nullable<int> nguoiTaoID, Nullable<System.DateTime> ngayTao, Nullable<int> tinhTrang, Nullable<int> nTID, Nullable<int> phongBanID, string hangMuc, Nullable<System.DateTime> thoiHan, Nullable<int> isNT, Nullable<int> kytruoc, string fileHosoDK, ObjectParameter iDTTT)
    {

        var noiDungParameter = noiDung != null ?
            new ObjectParameter("NoiDung", noiDung) :
            new ObjectParameter("NoiDung", typeof(string));


        var nguoiTaoIDParameter = nguoiTaoID.HasValue ?
            new ObjectParameter("NguoiTaoID", nguoiTaoID) :
            new ObjectParameter("NguoiTaoID", typeof(int));


        var ngayTaoParameter = ngayTao.HasValue ?
            new ObjectParameter("NgayTao", ngayTao) :
            new ObjectParameter("NgayTao", typeof(System.DateTime));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        var nTIDParameter = nTID.HasValue ?
            new ObjectParameter("NTID", nTID) :
            new ObjectParameter("NTID", typeof(int));


        var phongBanIDParameter = phongBanID.HasValue ?
            new ObjectParameter("PhongBanID", phongBanID) :
            new ObjectParameter("PhongBanID", typeof(int));


        var hangMucParameter = hangMuc != null ?
            new ObjectParameter("HangMuc", hangMuc) :
            new ObjectParameter("HangMuc", typeof(string));


        var thoiHanParameter = thoiHan.HasValue ?
            new ObjectParameter("ThoiHan", thoiHan) :
            new ObjectParameter("ThoiHan", typeof(System.DateTime));


        var isNTParameter = isNT.HasValue ?
            new ObjectParameter("isNT", isNT) :
            new ObjectParameter("isNT", typeof(int));


        var kytruocParameter = kytruoc.HasValue ?
            new ObjectParameter("kytruoc", kytruoc) :
            new ObjectParameter("kytruoc", typeof(int));


        var fileHosoDKParameter = fileHosoDK != null ?
            new ObjectParameter("FileHosoDK", fileHosoDK) :
            new ObjectParameter("FileHosoDK", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_CarteTemporaire_insert", noiDungParameter, nguoiTaoIDParameter, ngayTaoParameter, tinhTrangParameter, nTIDParameter, phongBanIDParameter, hangMucParameter, thoiHanParameter, isNTParameter, kytruocParameter, fileHosoDKParameter, iDTTT);
    }


    public virtual ObjectResult<NT_CarteTemporaire_Select_Result> NT_CarteTemporaire_Select(string search)
    {

        var searchParameter = search != null ?
            new ObjectParameter("search", search) :
            new ObjectParameter("search", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NT_CarteTemporaire_Select_Result>("NT_CarteTemporaire_Select", searchParameter);
    }


    public virtual int NT_CarteTemporaire_update(Nullable<int> iDTTT, string noiDung, Nullable<int> nguoiTaoID, Nullable<System.DateTime> ngayTao, Nullable<int> tinhTrang, Nullable<int> nTID, Nullable<int> phongBanID, string hangMuc, Nullable<System.DateTime> thoiHan, Nullable<int> kytruoc, string fileHosoDK)
    {

        var iDTTTParameter = iDTTT.HasValue ?
            new ObjectParameter("IDTTT", iDTTT) :
            new ObjectParameter("IDTTT", typeof(int));


        var noiDungParameter = noiDung != null ?
            new ObjectParameter("NoiDung", noiDung) :
            new ObjectParameter("NoiDung", typeof(string));


        var nguoiTaoIDParameter = nguoiTaoID.HasValue ?
            new ObjectParameter("NguoiTaoID", nguoiTaoID) :
            new ObjectParameter("NguoiTaoID", typeof(int));


        var ngayTaoParameter = ngayTao.HasValue ?
            new ObjectParameter("NgayTao", ngayTao) :
            new ObjectParameter("NgayTao", typeof(System.DateTime));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        var nTIDParameter = nTID.HasValue ?
            new ObjectParameter("NTID", nTID) :
            new ObjectParameter("NTID", typeof(int));


        var phongBanIDParameter = phongBanID.HasValue ?
            new ObjectParameter("PhongBanID", phongBanID) :
            new ObjectParameter("PhongBanID", typeof(int));


        var hangMucParameter = hangMuc != null ?
            new ObjectParameter("HangMuc", hangMuc) :
            new ObjectParameter("HangMuc", typeof(string));


        var thoiHanParameter = thoiHan.HasValue ?
            new ObjectParameter("ThoiHan", thoiHan) :
            new ObjectParameter("ThoiHan", typeof(System.DateTime));


        var kytruocParameter = kytruoc.HasValue ?
            new ObjectParameter("kytruoc", kytruoc) :
            new ObjectParameter("kytruoc", typeof(int));


        var fileHosoDKParameter = fileHosoDK != null ?
            new ObjectParameter("FileHosoDK", fileHosoDK) :
            new ObjectParameter("FileHosoDK", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_CarteTemporaire_update", iDTTTParameter, noiDungParameter, nguoiTaoIDParameter, ngayTaoParameter, tinhTrangParameter, nTIDParameter, phongBanIDParameter, hangMucParameter, thoiHanParameter, kytruocParameter, fileHosoDKParameter);
    }


    public virtual int NT_CarteTemporaire_Update_XL(Nullable<int> iDTTT, Nullable<int> tinhTrang)
    {

        var iDTTTParameter = iDTTT.HasValue ?
            new ObjectParameter("IDTTT", iDTTT) :
            new ObjectParameter("IDTTT", typeof(int));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_CarteTemporaire_Update_XL", iDTTTParameter, tinhTrangParameter);
    }


    public virtual int NT_ContactEquipment_delete(Nullable<int> iDTBNT)
    {

        var iDTBNTParameter = iDTBNT.HasValue ?
            new ObjectParameter("IDTBNT", iDTBNT) :
            new ObjectParameter("IDTBNT", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_ContactEquipment_delete", iDTBNTParameter);
    }


    public virtual int NT_ContactEquipment_insert(string nameEquipment, string indentifierContact, string bienSoXe, Nullable<int> iDContact, string @operator, Nullable<int> iDDepartment, Nullable<int> cavet, Nullable<System.DateTime> ngayHetHanDK, Nullable<System.DateTime> ngayHetHanKD, Nullable<System.DateTime> ngayHetHanBHX, Nullable<int> cCHV, Nullable<System.DateTime> ngayHetHanTAT, Nullable<System.DateTime> ngayHetHanVCHHChayNo, Nullable<System.DateTime> ngayHetHanCNKD, string chungChiPCCCCNCH, string chungChiVCHHCHCN, Nullable<System.DateTime> startDate, string iDKV, string nguoiNhap, Nullable<int> tinhTrang, string ghiChu, string fileUpload, Nullable<int> iDMDD, string soKhung, Nullable<System.DateTime> thoiHanTheTu, Nullable<System.DateTime> thoiHanTheRVTX, string capMoi, string giaHan, string matThe, string capNhatThongTin, string baoLanh, Nullable<System.DateTime> ngayChinhSua, string fileTheTu)
    {

        var nameEquipmentParameter = nameEquipment != null ?
            new ObjectParameter("NameEquipment", nameEquipment) :
            new ObjectParameter("NameEquipment", typeof(string));


        var indentifierContactParameter = indentifierContact != null ?
            new ObjectParameter("IndentifierContact", indentifierContact) :
            new ObjectParameter("IndentifierContact", typeof(string));


        var bienSoXeParameter = bienSoXe != null ?
            new ObjectParameter("BienSoXe", bienSoXe) :
            new ObjectParameter("BienSoXe", typeof(string));


        var iDContactParameter = iDContact.HasValue ?
            new ObjectParameter("IDContact", iDContact) :
            new ObjectParameter("IDContact", typeof(int));


        var operatorParameter = @operator != null ?
            new ObjectParameter("Operator", @operator) :
            new ObjectParameter("Operator", typeof(string));


        var iDDepartmentParameter = iDDepartment.HasValue ?
            new ObjectParameter("IDDepartment", iDDepartment) :
            new ObjectParameter("IDDepartment", typeof(int));


        var cavetParameter = cavet.HasValue ?
            new ObjectParameter("Cavet", cavet) :
            new ObjectParameter("Cavet", typeof(int));


        var ngayHetHanDKParameter = ngayHetHanDK.HasValue ?
            new ObjectParameter("NgayHetHanDK", ngayHetHanDK) :
            new ObjectParameter("NgayHetHanDK", typeof(System.DateTime));


        var ngayHetHanKDParameter = ngayHetHanKD.HasValue ?
            new ObjectParameter("NgayHetHanKD", ngayHetHanKD) :
            new ObjectParameter("NgayHetHanKD", typeof(System.DateTime));


        var ngayHetHanBHXParameter = ngayHetHanBHX.HasValue ?
            new ObjectParameter("NgayHetHanBHX", ngayHetHanBHX) :
            new ObjectParameter("NgayHetHanBHX", typeof(System.DateTime));


        var cCHVParameter = cCHV.HasValue ?
            new ObjectParameter("CCHV", cCHV) :
            new ObjectParameter("CCHV", typeof(int));


        var ngayHetHanTATParameter = ngayHetHanTAT.HasValue ?
            new ObjectParameter("NgayHetHanTAT", ngayHetHanTAT) :
            new ObjectParameter("NgayHetHanTAT", typeof(System.DateTime));


        var ngayHetHanVCHHChayNoParameter = ngayHetHanVCHHChayNo.HasValue ?
            new ObjectParameter("NgayHetHanVCHHChayNo", ngayHetHanVCHHChayNo) :
            new ObjectParameter("NgayHetHanVCHHChayNo", typeof(System.DateTime));


        var ngayHetHanCNKDParameter = ngayHetHanCNKD.HasValue ?
            new ObjectParameter("NgayHetHanCNKD", ngayHetHanCNKD) :
            new ObjectParameter("NgayHetHanCNKD", typeof(System.DateTime));


        var chungChiPCCCCNCHParameter = chungChiPCCCCNCH != null ?
            new ObjectParameter("ChungChiPCCCCNCH", chungChiPCCCCNCH) :
            new ObjectParameter("ChungChiPCCCCNCH", typeof(string));


        var chungChiVCHHCHCNParameter = chungChiVCHHCHCN != null ?
            new ObjectParameter("ChungChiVCHHCHCN", chungChiVCHHCHCN) :
            new ObjectParameter("ChungChiVCHHCHCN", typeof(string));


        var startDateParameter = startDate.HasValue ?
            new ObjectParameter("StartDate", startDate) :
            new ObjectParameter("StartDate", typeof(System.DateTime));


        var iDKVParameter = iDKV != null ?
            new ObjectParameter("IDKV", iDKV) :
            new ObjectParameter("IDKV", typeof(string));


        var nguoiNhapParameter = nguoiNhap != null ?
            new ObjectParameter("NguoiNhap", nguoiNhap) :
            new ObjectParameter("NguoiNhap", typeof(string));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        var fileUploadParameter = fileUpload != null ?
            new ObjectParameter("FileUpload", fileUpload) :
            new ObjectParameter("FileUpload", typeof(string));


        var iDMDDParameter = iDMDD.HasValue ?
            new ObjectParameter("IDMDD", iDMDD) :
            new ObjectParameter("IDMDD", typeof(int));


        var soKhungParameter = soKhung != null ?
            new ObjectParameter("SoKhung", soKhung) :
            new ObjectParameter("SoKhung", typeof(string));


        var thoiHanTheTuParameter = thoiHanTheTu.HasValue ?
            new ObjectParameter("ThoiHanTheTu", thoiHanTheTu) :
            new ObjectParameter("ThoiHanTheTu", typeof(System.DateTime));


        var thoiHanTheRVTXParameter = thoiHanTheRVTX.HasValue ?
            new ObjectParameter("ThoiHanTheRVTX", thoiHanTheRVTX) :
            new ObjectParameter("ThoiHanTheRVTX", typeof(System.DateTime));


        var capMoiParameter = capMoi != null ?
            new ObjectParameter("CapMoi", capMoi) :
            new ObjectParameter("CapMoi", typeof(string));


        var giaHanParameter = giaHan != null ?
            new ObjectParameter("GiaHan", giaHan) :
            new ObjectParameter("GiaHan", typeof(string));


        var matTheParameter = matThe != null ?
            new ObjectParameter("MatThe", matThe) :
            new ObjectParameter("MatThe", typeof(string));


        var capNhatThongTinParameter = capNhatThongTin != null ?
            new ObjectParameter("CapNhatThongTin", capNhatThongTin) :
            new ObjectParameter("CapNhatThongTin", typeof(string));


        var baoLanhParameter = baoLanh != null ?
            new ObjectParameter("BaoLanh", baoLanh) :
            new ObjectParameter("BaoLanh", typeof(string));


        var ngayChinhSuaParameter = ngayChinhSua.HasValue ?
            new ObjectParameter("NgayChinhSua", ngayChinhSua) :
            new ObjectParameter("NgayChinhSua", typeof(System.DateTime));


        var fileTheTuParameter = fileTheTu != null ?
            new ObjectParameter("FileTheTu", fileTheTu) :
            new ObjectParameter("FileTheTu", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_ContactEquipment_insert", nameEquipmentParameter, indentifierContactParameter, bienSoXeParameter, iDContactParameter, operatorParameter, iDDepartmentParameter, cavetParameter, ngayHetHanDKParameter, ngayHetHanKDParameter, ngayHetHanBHXParameter, cCHVParameter, ngayHetHanTATParameter, ngayHetHanVCHHChayNoParameter, ngayHetHanCNKDParameter, chungChiPCCCCNCHParameter, chungChiVCHHCHCNParameter, startDateParameter, iDKVParameter, nguoiNhapParameter, tinhTrangParameter, ghiChuParameter, fileUploadParameter, iDMDDParameter, soKhungParameter, thoiHanTheTuParameter, thoiHanTheRVTXParameter, capMoiParameter, giaHanParameter, matTheParameter, capNhatThongTinParameter, baoLanhParameter, ngayChinhSuaParameter, fileTheTuParameter);
    }


    public virtual ObjectResult<NT_ContactEquipment_Select_Result> NT_ContactEquipment_Select(string search)
    {

        var searchParameter = search != null ?
            new ObjectParameter("search", search) :
            new ObjectParameter("search", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NT_ContactEquipment_Select_Result>("NT_ContactEquipment_Select", searchParameter);
    }


    public virtual int NT_ContactEquipment_update(Nullable<int> iDTBNT, string nameEquipment, string indentifierContact, string bienSoXe, Nullable<int> iDContact, string @operator, Nullable<int> iDDepartment, Nullable<int> cavet, Nullable<System.DateTime> ngayHetHanDK, Nullable<System.DateTime> ngayHetHanKD, Nullable<System.DateTime> ngayHetHanBHX, Nullable<int> cCHV, Nullable<System.DateTime> ngayHetHanTAT, Nullable<System.DateTime> ngayHetHanVCHHChayNo, Nullable<System.DateTime> ngayHetHanCNKD, string chungChiPCCCCNCH, string chungChiVCHHCHCN, Nullable<System.DateTime> startDate, string iDKV, string nguoiNhap, Nullable<int> tinhTrang, string ghiChu, string fileUpload, Nullable<int> iDMDD, string soKhung, Nullable<System.DateTime> thoiHanTheTu, Nullable<System.DateTime> thoiHanTheRVTX, string capMoi, string giaHan, string matThe, string capNhatThongTin, string baoLanh, Nullable<System.DateTime> ngayChinhSua, string fileTheTu)
    {

        var iDTBNTParameter = iDTBNT.HasValue ?
            new ObjectParameter("IDTBNT", iDTBNT) :
            new ObjectParameter("IDTBNT", typeof(int));


        var nameEquipmentParameter = nameEquipment != null ?
            new ObjectParameter("NameEquipment", nameEquipment) :
            new ObjectParameter("NameEquipment", typeof(string));


        var indentifierContactParameter = indentifierContact != null ?
            new ObjectParameter("IndentifierContact", indentifierContact) :
            new ObjectParameter("IndentifierContact", typeof(string));


        var bienSoXeParameter = bienSoXe != null ?
            new ObjectParameter("BienSoXe", bienSoXe) :
            new ObjectParameter("BienSoXe", typeof(string));


        var iDContactParameter = iDContact.HasValue ?
            new ObjectParameter("IDContact", iDContact) :
            new ObjectParameter("IDContact", typeof(int));


        var operatorParameter = @operator != null ?
            new ObjectParameter("Operator", @operator) :
            new ObjectParameter("Operator", typeof(string));


        var iDDepartmentParameter = iDDepartment.HasValue ?
            new ObjectParameter("IDDepartment", iDDepartment) :
            new ObjectParameter("IDDepartment", typeof(int));


        var cavetParameter = cavet.HasValue ?
            new ObjectParameter("Cavet", cavet) :
            new ObjectParameter("Cavet", typeof(int));


        var ngayHetHanDKParameter = ngayHetHanDK.HasValue ?
            new ObjectParameter("NgayHetHanDK", ngayHetHanDK) :
            new ObjectParameter("NgayHetHanDK", typeof(System.DateTime));


        var ngayHetHanKDParameter = ngayHetHanKD.HasValue ?
            new ObjectParameter("NgayHetHanKD", ngayHetHanKD) :
            new ObjectParameter("NgayHetHanKD", typeof(System.DateTime));


        var ngayHetHanBHXParameter = ngayHetHanBHX.HasValue ?
            new ObjectParameter("NgayHetHanBHX", ngayHetHanBHX) :
            new ObjectParameter("NgayHetHanBHX", typeof(System.DateTime));


        var cCHVParameter = cCHV.HasValue ?
            new ObjectParameter("CCHV", cCHV) :
            new ObjectParameter("CCHV", typeof(int));


        var ngayHetHanTATParameter = ngayHetHanTAT.HasValue ?
            new ObjectParameter("NgayHetHanTAT", ngayHetHanTAT) :
            new ObjectParameter("NgayHetHanTAT", typeof(System.DateTime));


        var ngayHetHanVCHHChayNoParameter = ngayHetHanVCHHChayNo.HasValue ?
            new ObjectParameter("NgayHetHanVCHHChayNo", ngayHetHanVCHHChayNo) :
            new ObjectParameter("NgayHetHanVCHHChayNo", typeof(System.DateTime));


        var ngayHetHanCNKDParameter = ngayHetHanCNKD.HasValue ?
            new ObjectParameter("NgayHetHanCNKD", ngayHetHanCNKD) :
            new ObjectParameter("NgayHetHanCNKD", typeof(System.DateTime));


        var chungChiPCCCCNCHParameter = chungChiPCCCCNCH != null ?
            new ObjectParameter("ChungChiPCCCCNCH", chungChiPCCCCNCH) :
            new ObjectParameter("ChungChiPCCCCNCH", typeof(string));


        var chungChiVCHHCHCNParameter = chungChiVCHHCHCN != null ?
            new ObjectParameter("ChungChiVCHHCHCN", chungChiVCHHCHCN) :
            new ObjectParameter("ChungChiVCHHCHCN", typeof(string));


        var startDateParameter = startDate.HasValue ?
            new ObjectParameter("StartDate", startDate) :
            new ObjectParameter("StartDate", typeof(System.DateTime));


        var iDKVParameter = iDKV != null ?
            new ObjectParameter("IDKV", iDKV) :
            new ObjectParameter("IDKV", typeof(string));


        var nguoiNhapParameter = nguoiNhap != null ?
            new ObjectParameter("NguoiNhap", nguoiNhap) :
            new ObjectParameter("NguoiNhap", typeof(string));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        var fileUploadParameter = fileUpload != null ?
            new ObjectParameter("FileUpload", fileUpload) :
            new ObjectParameter("FileUpload", typeof(string));


        var iDMDDParameter = iDMDD.HasValue ?
            new ObjectParameter("IDMDD", iDMDD) :
            new ObjectParameter("IDMDD", typeof(int));


        var soKhungParameter = soKhung != null ?
            new ObjectParameter("SoKhung", soKhung) :
            new ObjectParameter("SoKhung", typeof(string));


        var thoiHanTheTuParameter = thoiHanTheTu.HasValue ?
            new ObjectParameter("ThoiHanTheTu", thoiHanTheTu) :
            new ObjectParameter("ThoiHanTheTu", typeof(System.DateTime));


        var thoiHanTheRVTXParameter = thoiHanTheRVTX.HasValue ?
            new ObjectParameter("ThoiHanTheRVTX", thoiHanTheRVTX) :
            new ObjectParameter("ThoiHanTheRVTX", typeof(System.DateTime));


        var capMoiParameter = capMoi != null ?
            new ObjectParameter("CapMoi", capMoi) :
            new ObjectParameter("CapMoi", typeof(string));


        var giaHanParameter = giaHan != null ?
            new ObjectParameter("GiaHan", giaHan) :
            new ObjectParameter("GiaHan", typeof(string));


        var matTheParameter = matThe != null ?
            new ObjectParameter("MatThe", matThe) :
            new ObjectParameter("MatThe", typeof(string));


        var capNhatThongTinParameter = capNhatThongTin != null ?
            new ObjectParameter("CapNhatThongTin", capNhatThongTin) :
            new ObjectParameter("CapNhatThongTin", typeof(string));


        var baoLanhParameter = baoLanh != null ?
            new ObjectParameter("BaoLanh", baoLanh) :
            new ObjectParameter("BaoLanh", typeof(string));


        var ngayChinhSuaParameter = ngayChinhSua.HasValue ?
            new ObjectParameter("NgayChinhSua", ngayChinhSua) :
            new ObjectParameter("NgayChinhSua", typeof(System.DateTime));


        var fileTheTuParameter = fileTheTu != null ?
            new ObjectParameter("FileTheTu", fileTheTu) :
            new ObjectParameter("FileTheTu", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_ContactEquipment_update", iDTBNTParameter, nameEquipmentParameter, indentifierContactParameter, bienSoXeParameter, iDContactParameter, operatorParameter, iDDepartmentParameter, cavetParameter, ngayHetHanDKParameter, ngayHetHanKDParameter, ngayHetHanBHXParameter, cCHVParameter, ngayHetHanTATParameter, ngayHetHanVCHHChayNoParameter, ngayHetHanCNKDParameter, chungChiPCCCCNCHParameter, chungChiVCHHCHCNParameter, startDateParameter, iDKVParameter, nguoiNhapParameter, tinhTrangParameter, ghiChuParameter, fileUploadParameter, iDMDDParameter, soKhungParameter, thoiHanTheTuParameter, thoiHanTheRVTXParameter, capMoiParameter, giaHanParameter, matTheParameter, capNhatThongTinParameter, baoLanhParameter, ngayChinhSuaParameter, fileTheTuParameter);
    }


    public virtual int NT_ContactEquipment_update_file(Nullable<int> iDTBNT, string fileUpload, string fileTheTu)
    {

        var iDTBNTParameter = iDTBNT.HasValue ?
            new ObjectParameter("IDTBNT", iDTBNT) :
            new ObjectParameter("IDTBNT", typeof(int));


        var fileUploadParameter = fileUpload != null ?
            new ObjectParameter("FileUpload", fileUpload) :
            new ObjectParameter("FileUpload", typeof(string));


        var fileTheTuParameter = fileTheTu != null ?
            new ObjectParameter("FileTheTu", fileTheTu) :
            new ObjectParameter("FileTheTu", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_ContactEquipment_update_file", iDTBNTParameter, fileUploadParameter, fileTheTuParameter);
    }


    public virtual int NT_DetailCarteTemporaire_Create(string hoVaTen, string cCCD, Nullable<System.DateTime> ngaySinh, string sdt, string bienSo, Nullable<int> cong, string ghiChu, Nullable<int> iDTTT, string chucVu, Nullable<int> loaiPT, string soPhieuDKVTTS, string vTTSChuaDK, string vTTheoPVCC, string soLanRaVao)
    {

        var hoVaTenParameter = hoVaTen != null ?
            new ObjectParameter("HoVaTen", hoVaTen) :
            new ObjectParameter("HoVaTen", typeof(string));


        var cCCDParameter = cCCD != null ?
            new ObjectParameter("CCCD", cCCD) :
            new ObjectParameter("CCCD", typeof(string));


        var ngaySinhParameter = ngaySinh.HasValue ?
            new ObjectParameter("NgaySinh", ngaySinh) :
            new ObjectParameter("NgaySinh", typeof(System.DateTime));


        var sdtParameter = sdt != null ?
            new ObjectParameter("Sdt", sdt) :
            new ObjectParameter("Sdt", typeof(string));


        var bienSoParameter = bienSo != null ?
            new ObjectParameter("BienSo", bienSo) :
            new ObjectParameter("BienSo", typeof(string));


        var congParameter = cong.HasValue ?
            new ObjectParameter("Cong", cong) :
            new ObjectParameter("Cong", typeof(int));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        var iDTTTParameter = iDTTT.HasValue ?
            new ObjectParameter("IDTTT", iDTTT) :
            new ObjectParameter("IDTTT", typeof(int));


        var chucVuParameter = chucVu != null ?
            new ObjectParameter("ChucVu", chucVu) :
            new ObjectParameter("ChucVu", typeof(string));


        var loaiPTParameter = loaiPT.HasValue ?
            new ObjectParameter("LoaiPT", loaiPT) :
            new ObjectParameter("LoaiPT", typeof(int));


        var soPhieuDKVTTSParameter = soPhieuDKVTTS != null ?
            new ObjectParameter("SoPhieuDKVTTS", soPhieuDKVTTS) :
            new ObjectParameter("SoPhieuDKVTTS", typeof(string));


        var vTTSChuaDKParameter = vTTSChuaDK != null ?
            new ObjectParameter("VTTSChuaDK", vTTSChuaDK) :
            new ObjectParameter("VTTSChuaDK", typeof(string));


        var vTTheoPVCCParameter = vTTheoPVCC != null ?
            new ObjectParameter("VTTheoPVCC", vTTheoPVCC) :
            new ObjectParameter("VTTheoPVCC", typeof(string));


        var soLanRaVaoParameter = soLanRaVao != null ?
            new ObjectParameter("SoLanRaVao", soLanRaVao) :
            new ObjectParameter("SoLanRaVao", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_DetailCarteTemporaire_Create", hoVaTenParameter, cCCDParameter, ngaySinhParameter, sdtParameter, bienSoParameter, congParameter, ghiChuParameter, iDTTTParameter, chucVuParameter, loaiPTParameter, soPhieuDKVTTSParameter, vTTSChuaDKParameter, vTTheoPVCCParameter, soLanRaVaoParameter);
    }


    public virtual int NT_DetailCarteTemporaire_delete(Nullable<int> iDCTTTT)
    {

        var iDCTTTTParameter = iDCTTTT.HasValue ?
            new ObjectParameter("IDCTTTT", iDCTTTT) :
            new ObjectParameter("IDCTTTT", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_DetailCarteTemporaire_delete", iDCTTTTParameter);
    }


    public virtual int NT_DetailCarteTemporaire_insert(string hoVaTen, string cCCD, Nullable<System.DateTime> ngaySinh, Nullable<int> mucDich, string sdt, string bienSo, Nullable<int> cong, string ghiChu, Nullable<int> iDTTT)
    {

        var hoVaTenParameter = hoVaTen != null ?
            new ObjectParameter("HoVaTen", hoVaTen) :
            new ObjectParameter("HoVaTen", typeof(string));


        var cCCDParameter = cCCD != null ?
            new ObjectParameter("CCCD", cCCD) :
            new ObjectParameter("CCCD", typeof(string));


        var ngaySinhParameter = ngaySinh.HasValue ?
            new ObjectParameter("NgaySinh", ngaySinh) :
            new ObjectParameter("NgaySinh", typeof(System.DateTime));


        var mucDichParameter = mucDich.HasValue ?
            new ObjectParameter("MucDich", mucDich) :
            new ObjectParameter("MucDich", typeof(int));


        var sdtParameter = sdt != null ?
            new ObjectParameter("Sdt", sdt) :
            new ObjectParameter("Sdt", typeof(string));


        var bienSoParameter = bienSo != null ?
            new ObjectParameter("BienSo", bienSo) :
            new ObjectParameter("BienSo", typeof(string));


        var congParameter = cong.HasValue ?
            new ObjectParameter("Cong", cong) :
            new ObjectParameter("Cong", typeof(int));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        var iDTTTParameter = iDTTT.HasValue ?
            new ObjectParameter("IDTTT", iDTTT) :
            new ObjectParameter("IDTTT", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_DetailCarteTemporaire_insert", hoVaTenParameter, cCCDParameter, ngaySinhParameter, mucDichParameter, sdtParameter, bienSoParameter, congParameter, ghiChuParameter, iDTTTParameter);
    }


    public virtual int NT_DetailCarteTemporaire_update(Nullable<int> iDCTTTT, string hoVaTen, string cCCD, Nullable<System.DateTime> ngaySinh, Nullable<int> mucDich, string sdt, string bienSo, Nullable<int> cong, string ghiChu, Nullable<int> iDTTT)
    {

        var iDCTTTTParameter = iDCTTTT.HasValue ?
            new ObjectParameter("IDCTTTT", iDCTTTT) :
            new ObjectParameter("IDCTTTT", typeof(int));


        var hoVaTenParameter = hoVaTen != null ?
            new ObjectParameter("HoVaTen", hoVaTen) :
            new ObjectParameter("HoVaTen", typeof(string));


        var cCCDParameter = cCCD != null ?
            new ObjectParameter("CCCD", cCCD) :
            new ObjectParameter("CCCD", typeof(string));


        var ngaySinhParameter = ngaySinh.HasValue ?
            new ObjectParameter("NgaySinh", ngaySinh) :
            new ObjectParameter("NgaySinh", typeof(System.DateTime));


        var mucDichParameter = mucDich.HasValue ?
            new ObjectParameter("MucDich", mucDich) :
            new ObjectParameter("MucDich", typeof(int));


        var sdtParameter = sdt != null ?
            new ObjectParameter("Sdt", sdt) :
            new ObjectParameter("Sdt", typeof(string));


        var bienSoParameter = bienSo != null ?
            new ObjectParameter("BienSo", bienSo) :
            new ObjectParameter("BienSo", typeof(string));


        var congParameter = cong.HasValue ?
            new ObjectParameter("Cong", cong) :
            new ObjectParameter("Cong", typeof(int));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        var iDTTTParameter = iDTTT.HasValue ?
            new ObjectParameter("IDTTT", iDTTT) :
            new ObjectParameter("IDTTT", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_DetailCarteTemporaire_update", iDCTTTTParameter, hoVaTenParameter, cCCDParameter, ngaySinhParameter, mucDichParameter, sdtParameter, bienSoParameter, congParameter, ghiChuParameter, iDTTTParameter);
    }


    public virtual int NT_DetailCarteTemporaire_update1(Nullable<int> iDCTTTT, string hoVaTen, string cCCD, Nullable<System.DateTime> ngaySinh, Nullable<int> loaiPTID, string chucVu, string sdt, string bienSo, Nullable<int> cong, string ghiChu, string soPhieuDKVTTS, string vTTSChuaDK, string vTTheoPVCC, string soLanRaVao)
    {

        var iDCTTTTParameter = iDCTTTT.HasValue ?
            new ObjectParameter("IDCTTTT", iDCTTTT) :
            new ObjectParameter("IDCTTTT", typeof(int));


        var hoVaTenParameter = hoVaTen != null ?
            new ObjectParameter("HoVaTen", hoVaTen) :
            new ObjectParameter("HoVaTen", typeof(string));


        var cCCDParameter = cCCD != null ?
            new ObjectParameter("CCCD", cCCD) :
            new ObjectParameter("CCCD", typeof(string));


        var ngaySinhParameter = ngaySinh.HasValue ?
            new ObjectParameter("NgaySinh", ngaySinh) :
            new ObjectParameter("NgaySinh", typeof(System.DateTime));


        var loaiPTIDParameter = loaiPTID.HasValue ?
            new ObjectParameter("LoaiPTID", loaiPTID) :
            new ObjectParameter("LoaiPTID", typeof(int));


        var chucVuParameter = chucVu != null ?
            new ObjectParameter("ChucVu", chucVu) :
            new ObjectParameter("ChucVu", typeof(string));


        var sdtParameter = sdt != null ?
            new ObjectParameter("Sdt", sdt) :
            new ObjectParameter("Sdt", typeof(string));


        var bienSoParameter = bienSo != null ?
            new ObjectParameter("BienSo", bienSo) :
            new ObjectParameter("BienSo", typeof(string));


        var congParameter = cong.HasValue ?
            new ObjectParameter("Cong", cong) :
            new ObjectParameter("Cong", typeof(int));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        var soPhieuDKVTTSParameter = soPhieuDKVTTS != null ?
            new ObjectParameter("SoPhieuDKVTTS", soPhieuDKVTTS) :
            new ObjectParameter("SoPhieuDKVTTS", typeof(string));


        var vTTSChuaDKParameter = vTTSChuaDK != null ?
            new ObjectParameter("VTTSChuaDK", vTTSChuaDK) :
            new ObjectParameter("VTTSChuaDK", typeof(string));


        var vTTheoPVCCParameter = vTTheoPVCC != null ?
            new ObjectParameter("VTTheoPVCC", vTTheoPVCC) :
            new ObjectParameter("VTTheoPVCC", typeof(string));


        var soLanRaVaoParameter = soLanRaVao != null ?
            new ObjectParameter("SoLanRaVao", soLanRaVao) :
            new ObjectParameter("SoLanRaVao", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_DetailCarteTemporaire_update1", iDCTTTTParameter, hoVaTenParameter, cCCDParameter, ngaySinhParameter, loaiPTIDParameter, chucVuParameter, sdtParameter, bienSoParameter, congParameter, ghiChuParameter, soPhieuDKVTTSParameter, vTTSChuaDKParameter, vTTheoPVCCParameter, soLanRaVaoParameter);
    }


    public virtual int NT_Handle_insert(Nullable<int> iDTTT, Nullable<int> iDCTTTT)
    {

        var iDTTTParameter = iDTTT.HasValue ?
            new ObjectParameter("IDTTT", iDTTT) :
            new ObjectParameter("IDTTT", typeof(int));


        var iDCTTTTParameter = iDCTTTT.HasValue ?
            new ObjectParameter("IDCTTTT", iDCTTTT) :
            new ObjectParameter("IDCTTTT", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_Handle_insert", iDTTTParameter, iDCTTTTParameter);
    }


    public virtual int NT_Handle_update(Nullable<int> iDXL, Nullable<int> nguoiXuLy, Nullable<System.DateTime> thoiGianXuLy, Nullable<int> iDThe)
    {

        var iDXLParameter = iDXL.HasValue ?
            new ObjectParameter("IDXL", iDXL) :
            new ObjectParameter("IDXL", typeof(int));


        var nguoiXuLyParameter = nguoiXuLy.HasValue ?
            new ObjectParameter("NguoiXuLy", nguoiXuLy) :
            new ObjectParameter("NguoiXuLy", typeof(int));


        var thoiGianXuLyParameter = thoiGianXuLy.HasValue ?
            new ObjectParameter("ThoiGianXuLy", thoiGianXuLy) :
            new ObjectParameter("ThoiGianXuLy", typeof(System.DateTime));


        var iDTheParameter = iDThe.HasValue ?
            new ObjectParameter("IDThe", iDThe) :
            new ObjectParameter("IDThe", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_Handle_update", iDXLParameter, nguoiXuLyParameter, thoiGianXuLyParameter, iDTheParameter);
    }


    public virtual int NT_HistoryBlackList_insert(Nullable<int> nVVPID, Nullable<System.DateTime> ngayUpdate, Nullable<int> iDNVUpdate, Nullable<int> statusUpdate)
    {

        var nVVPIDParameter = nVVPID.HasValue ?
            new ObjectParameter("NVVPID", nVVPID) :
            new ObjectParameter("NVVPID", typeof(int));


        var ngayUpdateParameter = ngayUpdate.HasValue ?
            new ObjectParameter("NgayUpdate", ngayUpdate) :
            new ObjectParameter("NgayUpdate", typeof(System.DateTime));


        var iDNVUpdateParameter = iDNVUpdate.HasValue ?
            new ObjectParameter("IDNVUpdate", iDNVUpdate) :
            new ObjectParameter("IDNVUpdate", typeof(int));


        var statusUpdateParameter = statusUpdate.HasValue ?
            new ObjectParameter("StatusUpdate", statusUpdate) :
            new ObjectParameter("StatusUpdate", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_HistoryBlackList_insert", nVVPIDParameter, ngayUpdateParameter, iDNVUpdateParameter, statusUpdateParameter);
    }


    public virtual ObjectResult<NT_HistoryBlackList_Select_Result> NT_HistoryBlackList_Select(string search)
    {

        var searchParameter = search != null ?
            new ObjectParameter("search", search) :
            new ObjectParameter("search", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NT_HistoryBlackList_Select_Result>("NT_HistoryBlackList_Select", searchParameter);
    }


    public virtual int NT_HoatDongNV_insert(Nullable<int> iDNVNT, Nullable<int> iDNT, Nullable<System.DateTime> ngayCap, Nullable<System.DateTime> hanSuDung, string iDKV, Nullable<int> iDCA, string ghiChu)
    {

        var iDNVNTParameter = iDNVNT.HasValue ?
            new ObjectParameter("IDNVNT", iDNVNT) :
            new ObjectParameter("IDNVNT", typeof(int));


        var iDNTParameter = iDNT.HasValue ?
            new ObjectParameter("IDNT", iDNT) :
            new ObjectParameter("IDNT", typeof(int));


        var ngayCapParameter = ngayCap.HasValue ?
            new ObjectParameter("NgayCap", ngayCap) :
            new ObjectParameter("NgayCap", typeof(System.DateTime));


        var hanSuDungParameter = hanSuDung.HasValue ?
            new ObjectParameter("HanSuDung", hanSuDung) :
            new ObjectParameter("HanSuDung", typeof(System.DateTime));


        var iDKVParameter = iDKV != null ?
            new ObjectParameter("IDKV", iDKV) :
            new ObjectParameter("IDKV", typeof(string));


        var iDCAParameter = iDCA.HasValue ?
            new ObjectParameter("IDCA", iDCA) :
            new ObjectParameter("IDCA", typeof(int));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_HoatDongNV_insert", iDNVNTParameter, iDNTParameter, ngayCapParameter, hanSuDungParameter, iDKVParameter, iDCAParameter, ghiChuParameter);
    }


    public virtual int NT_NhanVienNT_delete(Nullable<int> iDNVNT)
    {

        var iDNVNTParameter = iDNVNT.HasValue ?
            new ObjectParameter("IDNVNT", iDNVNT) :
            new ObjectParameter("IDNVNT", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_NhanVienNT_delete", iDNVNTParameter);
    }


    public virtual int NT_NhanVienNT_insert(string hoTen, string cCCD, string cMND, string diaChi, Nullable<int> sdt, string soThe, Nullable<int> iDNT, Nullable<System.DateTime> ngayCap, Nullable<System.DateTime> hanSuDung, Nullable<int> chucVuID, Nullable<int> tTLV)
    {

        var hoTenParameter = hoTen != null ?
            new ObjectParameter("HoTen", hoTen) :
            new ObjectParameter("HoTen", typeof(string));


        var cCCDParameter = cCCD != null ?
            new ObjectParameter("CCCD", cCCD) :
            new ObjectParameter("CCCD", typeof(string));


        var cMNDParameter = cMND != null ?
            new ObjectParameter("CMND", cMND) :
            new ObjectParameter("CMND", typeof(string));


        var diaChiParameter = diaChi != null ?
            new ObjectParameter("DiaChi", diaChi) :
            new ObjectParameter("DiaChi", typeof(string));


        var sdtParameter = sdt.HasValue ?
            new ObjectParameter("Sdt", sdt) :
            new ObjectParameter("Sdt", typeof(int));


        var soTheParameter = soThe != null ?
            new ObjectParameter("SoThe", soThe) :
            new ObjectParameter("SoThe", typeof(string));


        var iDNTParameter = iDNT.HasValue ?
            new ObjectParameter("IDNT", iDNT) :
            new ObjectParameter("IDNT", typeof(int));


        var ngayCapParameter = ngayCap.HasValue ?
            new ObjectParameter("NgayCap", ngayCap) :
            new ObjectParameter("NgayCap", typeof(System.DateTime));


        var hanSuDungParameter = hanSuDung.HasValue ?
            new ObjectParameter("HanSuDung", hanSuDung) :
            new ObjectParameter("HanSuDung", typeof(System.DateTime));


        var chucVuIDParameter = chucVuID.HasValue ?
            new ObjectParameter("ChucVuID", chucVuID) :
            new ObjectParameter("ChucVuID", typeof(int));


        var tTLVParameter = tTLV.HasValue ?
            new ObjectParameter("TTLV", tTLV) :
            new ObjectParameter("TTLV", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_NhanVienNT_insert", hoTenParameter, cCCDParameter, cMNDParameter, diaChiParameter, sdtParameter, soTheParameter, iDNTParameter, ngayCapParameter, hanSuDungParameter, chucVuIDParameter, tTLVParameter);
    }


    public virtual int NT_NhanVienNT_insertall(string hoTen, string cCCD, string cMND, string diaChi, Nullable<int> sdt, string soThe, Nullable<int> iDNT, Nullable<System.DateTime> ngayCap, Nullable<System.DateTime> hanSuDung, Nullable<int> chucVuID, Nullable<int> tTLV, ObjectParameter iDNVNT)
    {

        var hoTenParameter = hoTen != null ?
            new ObjectParameter("HoTen", hoTen) :
            new ObjectParameter("HoTen", typeof(string));


        var cCCDParameter = cCCD != null ?
            new ObjectParameter("CCCD", cCCD) :
            new ObjectParameter("CCCD", typeof(string));


        var cMNDParameter = cMND != null ?
            new ObjectParameter("CMND", cMND) :
            new ObjectParameter("CMND", typeof(string));


        var diaChiParameter = diaChi != null ?
            new ObjectParameter("DiaChi", diaChi) :
            new ObjectParameter("DiaChi", typeof(string));


        var sdtParameter = sdt.HasValue ?
            new ObjectParameter("Sdt", sdt) :
            new ObjectParameter("Sdt", typeof(int));


        var soTheParameter = soThe != null ?
            new ObjectParameter("SoThe", soThe) :
            new ObjectParameter("SoThe", typeof(string));


        var iDNTParameter = iDNT.HasValue ?
            new ObjectParameter("IDNT", iDNT) :
            new ObjectParameter("IDNT", typeof(int));


        var ngayCapParameter = ngayCap.HasValue ?
            new ObjectParameter("NgayCap", ngayCap) :
            new ObjectParameter("NgayCap", typeof(System.DateTime));


        var hanSuDungParameter = hanSuDung.HasValue ?
            new ObjectParameter("HanSuDung", hanSuDung) :
            new ObjectParameter("HanSuDung", typeof(System.DateTime));


        var chucVuIDParameter = chucVuID.HasValue ?
            new ObjectParameter("ChucVuID", chucVuID) :
            new ObjectParameter("ChucVuID", typeof(int));


        var tTLVParameter = tTLV.HasValue ?
            new ObjectParameter("TTLV", tTLV) :
            new ObjectParameter("TTLV", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_NhanVienNT_insertall", hoTenParameter, cCCDParameter, cMNDParameter, diaChiParameter, sdtParameter, soTheParameter, iDNTParameter, ngayCapParameter, hanSuDungParameter, chucVuIDParameter, tTLVParameter, iDNVNT);
    }


    public virtual int NT_NhanVienNT_lock(Nullable<int> iDNVNT, Nullable<int> tTLV)
    {

        var iDNVNTParameter = iDNVNT.HasValue ?
            new ObjectParameter("IDNVNT", iDNVNT) :
            new ObjectParameter("IDNVNT", typeof(int));


        var tTLVParameter = tTLV.HasValue ?
            new ObjectParameter("TTLV", tTLV) :
            new ObjectParameter("TTLV", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_NhanVienNT_lock", iDNVNTParameter, tTLVParameter);
    }


    public virtual ObjectResult<NT_NhanVienNT_Select_Result> NT_NhanVienNT_Select(string search)
    {

        var searchParameter = search != null ?
            new ObjectParameter("search", search) :
            new ObjectParameter("search", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NT_NhanVienNT_Select_Result>("NT_NhanVienNT_Select", searchParameter);
    }


    public virtual int NT_NhanVienNT_update(Nullable<int> iDNVNT, string hoTen, string cCCD, string cMND, string diaChi, Nullable<int> sdt, string soThe, Nullable<int> iDNT, Nullable<System.DateTime> ngayCap, Nullable<System.DateTime> hanSuDung, Nullable<int> chucVuID, Nullable<int> tTLV)
    {

        var iDNVNTParameter = iDNVNT.HasValue ?
            new ObjectParameter("IDNVNT", iDNVNT) :
            new ObjectParameter("IDNVNT", typeof(int));


        var hoTenParameter = hoTen != null ?
            new ObjectParameter("HoTen", hoTen) :
            new ObjectParameter("HoTen", typeof(string));


        var cCCDParameter = cCCD != null ?
            new ObjectParameter("CCCD", cCCD) :
            new ObjectParameter("CCCD", typeof(string));


        var cMNDParameter = cMND != null ?
            new ObjectParameter("CMND", cMND) :
            new ObjectParameter("CMND", typeof(string));


        var diaChiParameter = diaChi != null ?
            new ObjectParameter("DiaChi", diaChi) :
            new ObjectParameter("DiaChi", typeof(string));


        var sdtParameter = sdt.HasValue ?
            new ObjectParameter("Sdt", sdt) :
            new ObjectParameter("Sdt", typeof(int));


        var soTheParameter = soThe != null ?
            new ObjectParameter("SoThe", soThe) :
            new ObjectParameter("SoThe", typeof(string));


        var iDNTParameter = iDNT.HasValue ?
            new ObjectParameter("IDNT", iDNT) :
            new ObjectParameter("IDNT", typeof(int));


        var ngayCapParameter = ngayCap.HasValue ?
            new ObjectParameter("NgayCap", ngayCap) :
            new ObjectParameter("NgayCap", typeof(System.DateTime));


        var hanSuDungParameter = hanSuDung.HasValue ?
            new ObjectParameter("HanSuDung", hanSuDung) :
            new ObjectParameter("HanSuDung", typeof(System.DateTime));


        var chucVuIDParameter = chucVuID.HasValue ?
            new ObjectParameter("ChucVuID", chucVuID) :
            new ObjectParameter("ChucVuID", typeof(int));


        var tTLVParameter = tTLV.HasValue ?
            new ObjectParameter("TTLV", tTLV) :
            new ObjectParameter("TTLV", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_NhanVienNT_update", iDNVNTParameter, hoTenParameter, cCCDParameter, cMNDParameter, diaChiParameter, sdtParameter, soTheParameter, iDNTParameter, ngayCapParameter, hanSuDungParameter, chucVuIDParameter, tTLVParameter);
    }


    public virtual int NT_NhanVienNT_updateday(Nullable<int> iDNVNT, Nullable<System.DateTime> ngayCap, Nullable<System.DateTime> hanSuDung)
    {

        var iDNVNTParameter = iDNVNT.HasValue ?
            new ObjectParameter("IDNVNT", iDNVNT) :
            new ObjectParameter("IDNVNT", typeof(int));


        var ngayCapParameter = ngayCap.HasValue ?
            new ObjectParameter("NgayCap", ngayCap) :
            new ObjectParameter("NgayCap", typeof(System.DateTime));


        var hanSuDungParameter = hanSuDung.HasValue ?
            new ObjectParameter("HanSuDung", hanSuDung) :
            new ObjectParameter("HanSuDung", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_NhanVienNT_updateday", iDNVNTParameter, ngayCapParameter, hanSuDungParameter);
    }


    public virtual int NT_NhanVienVP_delete(Nullable<int> iDNVVP)
    {

        var iDNVVPParameter = iDNVVP.HasValue ?
            new ObjectParameter("IDNVVP", iDNVVP) :
            new ObjectParameter("IDNVVP", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_NhanVienVP_delete", iDNVVPParameter);
    }


    public virtual int NT_NhanVienVP_insert(string hoTen, string cCCD, string cMND, Nullable<System.DateTime> ngaySinh, string lyDoCam, string ghiChu, Nullable<System.DateTime> createDay, Nullable<int> createIDNV, Nullable<int> tinhTrang)
    {

        var hoTenParameter = hoTen != null ?
            new ObjectParameter("HoTen", hoTen) :
            new ObjectParameter("HoTen", typeof(string));


        var cCCDParameter = cCCD != null ?
            new ObjectParameter("CCCD", cCCD) :
            new ObjectParameter("CCCD", typeof(string));


        var cMNDParameter = cMND != null ?
            new ObjectParameter("CMND", cMND) :
            new ObjectParameter("CMND", typeof(string));


        var ngaySinhParameter = ngaySinh.HasValue ?
            new ObjectParameter("NgaySinh", ngaySinh) :
            new ObjectParameter("NgaySinh", typeof(System.DateTime));


        var lyDoCamParameter = lyDoCam != null ?
            new ObjectParameter("LyDoCam", lyDoCam) :
            new ObjectParameter("LyDoCam", typeof(string));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        var createDayParameter = createDay.HasValue ?
            new ObjectParameter("CreateDay", createDay) :
            new ObjectParameter("CreateDay", typeof(System.DateTime));


        var createIDNVParameter = createIDNV.HasValue ?
            new ObjectParameter("CreateIDNV", createIDNV) :
            new ObjectParameter("CreateIDNV", typeof(int));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_NhanVienVP_insert", hoTenParameter, cCCDParameter, cMNDParameter, ngaySinhParameter, lyDoCamParameter, ghiChuParameter, createDayParameter, createIDNVParameter, tinhTrangParameter);
    }


    public virtual ObjectResult<NT_NhanVienVP_Select_Result> NT_NhanVienVP_Select(string search)
    {

        var searchParameter = search != null ?
            new ObjectParameter("search", search) :
            new ObjectParameter("search", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NT_NhanVienVP_Select_Result>("NT_NhanVienVP_Select", searchParameter);
    }


    public virtual int NT_NhanVienVP_update(Nullable<int> iDNVVP, string hoTen, string cCCD, Nullable<System.DateTime> ngaySinh, string lyDoCam, string ghiChu)
    {

        var iDNVVPParameter = iDNVVP.HasValue ?
            new ObjectParameter("IDNVVP", iDNVVP) :
            new ObjectParameter("IDNVVP", typeof(int));


        var hoTenParameter = hoTen != null ?
            new ObjectParameter("HoTen", hoTen) :
            new ObjectParameter("HoTen", typeof(string));


        var cCCDParameter = cCCD != null ?
            new ObjectParameter("CCCD", cCCD) :
            new ObjectParameter("CCCD", typeof(string));


        var ngaySinhParameter = ngaySinh.HasValue ?
            new ObjectParameter("NgaySinh", ngaySinh) :
            new ObjectParameter("NgaySinh", typeof(System.DateTime));


        var lyDoCamParameter = lyDoCam != null ?
            new ObjectParameter("LyDoCam", lyDoCam) :
            new ObjectParameter("LyDoCam", typeof(string));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_NhanVienVP_update", iDNVVPParameter, hoTenParameter, cCCDParameter, ngaySinhParameter, lyDoCamParameter, ghiChuParameter);
    }


    public virtual int NT_NhanVienVP_updateLock(Nullable<int> iDNVVP, Nullable<int> tinhTrang)
    {

        var iDNVVPParameter = iDNVVP.HasValue ?
            new ObjectParameter("IDNVVP", iDNVVP) :
            new ObjectParameter("IDNVVP", typeof(int));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_NhanVienVP_updateLock", iDNVVPParameter, tinhTrangParameter);
    }


    public virtual int NT_UserTemp_delete(Nullable<int> iD)
    {

        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_UserTemp_delete", iDParameter);
    }


    public virtual int NT_UserTemp_Img(Nullable<int> iD, string chuKy)
    {

        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));


        var chuKyParameter = chuKy != null ?
            new ObjectParameter("ChuKy", chuKy) :
            new ObjectParameter("ChuKy", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_UserTemp_Img", iDParameter, chuKyParameter);
    }


    public virtual int NT_UserTemp_insert(string userName, string matKhau, Nullable<int> iDNT, Nullable<int> tinhTrang)
    {

        var userNameParameter = userName != null ?
            new ObjectParameter("UserName", userName) :
            new ObjectParameter("UserName", typeof(string));


        var matKhauParameter = matKhau != null ?
            new ObjectParameter("MatKhau", matKhau) :
            new ObjectParameter("MatKhau", typeof(string));


        var iDNTParameter = iDNT.HasValue ?
            new ObjectParameter("IDNT", iDNT) :
            new ObjectParameter("IDNT", typeof(int));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_UserTemp_insert", userNameParameter, matKhauParameter, iDNTParameter, tinhTrangParameter);
    }


    public virtual int NT_UserTemp_Pass(Nullable<int> iD, string matKhau)
    {

        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));


        var matKhauParameter = matKhau != null ?
            new ObjectParameter("MatKhau", matKhau) :
            new ObjectParameter("MatKhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_UserTemp_Pass", iDParameter, matKhauParameter);
    }


    public virtual ObjectResult<NT_UserTemp_Select_Result> NT_UserTemp_Select(string search)
    {

        var searchParameter = search != null ?
            new ObjectParameter("search", search) :
            new ObjectParameter("search", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NT_UserTemp_Select_Result>("NT_UserTemp_Select", searchParameter);
    }


    public virtual int NT_UserTemp_update(Nullable<int> iD, string userName, string matKhau, Nullable<int> iDNT, Nullable<int> tinhTrang)
    {

        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));


        var userNameParameter = userName != null ?
            new ObjectParameter("UserName", userName) :
            new ObjectParameter("UserName", typeof(string));


        var matKhauParameter = matKhau != null ?
            new ObjectParameter("MatKhau", matKhau) :
            new ObjectParameter("MatKhau", typeof(string));


        var iDNTParameter = iDNT.HasValue ?
            new ObjectParameter("IDNT", iDNT) :
            new ObjectParameter("IDNT", typeof(int));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_UserTemp_update", iDParameter, userNameParameter, matKhauParameter, iDNTParameter, tinhTrangParameter);
    }


    public virtual int NT_UserTemp_updatePass(Nullable<int> iD, string matKhau)
    {

        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));


        var matKhauParameter = matKhau != null ?
            new ObjectParameter("MatKhau", matKhau) :
            new ObjectParameter("MatKhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_UserTemp_updatePass", iDParameter, matKhauParameter);
    }


    public virtual int sp_CarteTemp_Update1(Nullable<int> id, Nullable<int> tinhTrang, Nullable<System.DateTime> date)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        var dateParameter = date.HasValue ?
            new ObjectParameter("date", date) :
            new ObjectParameter("date", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CarteTemp_Update1", idParameter, tinhTrangParameter, dateParameter);
    }


    public virtual int sp_NT_CarteTemporaire_update(Nullable<int> iDTTT, string noiDung, Nullable<int> nguoiTaoID, Nullable<System.DateTime> ngayTao, Nullable<int> tinhTrang, Nullable<int> nTID, Nullable<int> phongBanID, string hangMuc, Nullable<System.DateTime> thoiHan, string ghiChu, Nullable<int> isNT)
    {

        var iDTTTParameter = iDTTT.HasValue ?
            new ObjectParameter("IDTTT", iDTTT) :
            new ObjectParameter("IDTTT", typeof(int));


        var noiDungParameter = noiDung != null ?
            new ObjectParameter("NoiDung", noiDung) :
            new ObjectParameter("NoiDung", typeof(string));


        var nguoiTaoIDParameter = nguoiTaoID.HasValue ?
            new ObjectParameter("NguoiTaoID", nguoiTaoID) :
            new ObjectParameter("NguoiTaoID", typeof(int));


        var ngayTaoParameter = ngayTao.HasValue ?
            new ObjectParameter("NgayTao", ngayTao) :
            new ObjectParameter("NgayTao", typeof(System.DateTime));


        var tinhTrangParameter = tinhTrang.HasValue ?
            new ObjectParameter("TinhTrang", tinhTrang) :
            new ObjectParameter("TinhTrang", typeof(int));


        var nTIDParameter = nTID.HasValue ?
            new ObjectParameter("NTID", nTID) :
            new ObjectParameter("NTID", typeof(int));


        var phongBanIDParameter = phongBanID.HasValue ?
            new ObjectParameter("PhongBanID", phongBanID) :
            new ObjectParameter("PhongBanID", typeof(int));


        var hangMucParameter = hangMuc != null ?
            new ObjectParameter("HangMuc", hangMuc) :
            new ObjectParameter("HangMuc", typeof(string));


        var thoiHanParameter = thoiHan.HasValue ?
            new ObjectParameter("ThoiHan", thoiHan) :
            new ObjectParameter("ThoiHan", typeof(System.DateTime));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        var isNTParameter = isNT.HasValue ?
            new ObjectParameter("isNT", isNT) :
            new ObjectParameter("isNT", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NT_CarteTemporaire_update", iDTTTParameter, noiDungParameter, nguoiTaoIDParameter, ngayTaoParameter, tinhTrangParameter, nTIDParameter, phongBanIDParameter, hangMucParameter, thoiHanParameter, ghiChuParameter, isNTParameter);
    }


    public virtual int sp_NTCarteTemp(Nullable<int> tTTID, Nullable<int> capduyet, Nullable<int> tinhTrangID, Nullable<int> nhanVienID, Nullable<System.DateTime> ngayDuyet, string ghiChu)
    {

        var tTTIDParameter = tTTID.HasValue ?
            new ObjectParameter("TTTID", tTTID) :
            new ObjectParameter("TTTID", typeof(int));


        var capduyetParameter = capduyet.HasValue ?
            new ObjectParameter("Capduyet", capduyet) :
            new ObjectParameter("Capduyet", typeof(int));


        var tinhTrangIDParameter = tinhTrangID.HasValue ?
            new ObjectParameter("TinhTrangID", tinhTrangID) :
            new ObjectParameter("TinhTrangID", typeof(int));


        var nhanVienIDParameter = nhanVienID.HasValue ?
            new ObjectParameter("NhanVienID", nhanVienID) :
            new ObjectParameter("NhanVienID", typeof(int));


        var ngayDuyetParameter = ngayDuyet.HasValue ?
            new ObjectParameter("NgayDuyet", ngayDuyet) :
            new ObjectParameter("NgayDuyet", typeof(System.DateTime));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NTCarteTemp", tTTIDParameter, capduyetParameter, tinhTrangIDParameter, nhanVienIDParameter, ngayDuyetParameter, ghiChuParameter);
    }


    public virtual int sp_NTCarteTemp_Create(Nullable<int> tTTID, Nullable<int> capduyet, Nullable<int> tinhTrangID, Nullable<int> nhanVienID, Nullable<System.DateTime> ngayDuyet, string ghiChu)
    {

        var tTTIDParameter = tTTID.HasValue ?
            new ObjectParameter("TTTID", tTTID) :
            new ObjectParameter("TTTID", typeof(int));


        var capduyetParameter = capduyet.HasValue ?
            new ObjectParameter("Capduyet", capduyet) :
            new ObjectParameter("Capduyet", typeof(int));


        var tinhTrangIDParameter = tinhTrangID.HasValue ?
            new ObjectParameter("TinhTrangID", tinhTrangID) :
            new ObjectParameter("TinhTrangID", typeof(int));


        var nhanVienIDParameter = nhanVienID.HasValue ?
            new ObjectParameter("NhanVienID", nhanVienID) :
            new ObjectParameter("NhanVienID", typeof(int));


        var ngayDuyetParameter = ngayDuyet.HasValue ?
            new ObjectParameter("NgayDuyet", ngayDuyet) :
            new ObjectParameter("NgayDuyet", typeof(System.DateTime));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NTCarteTemp_Create", tTTIDParameter, capduyetParameter, tinhTrangIDParameter, nhanVienIDParameter, ngayDuyetParameter, ghiChuParameter);
    }


    public virtual int sp_NTCarteTemp_Delete(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NTCarteTemp_Delete", idParameter);
    }


    public virtual int sp_NTCarteTemp_Update(Nullable<int> iDDTT, Nullable<int> capDuyet, Nullable<int> tinhTrangID, Nullable<int> nhanVienID, Nullable<System.DateTime> ngayDuyet, string ghiChu)
    {

        var iDDTTParameter = iDDTT.HasValue ?
            new ObjectParameter("IDDTT", iDDTT) :
            new ObjectParameter("IDDTT", typeof(int));


        var capDuyetParameter = capDuyet.HasValue ?
            new ObjectParameter("CapDuyet", capDuyet) :
            new ObjectParameter("CapDuyet", typeof(int));


        var tinhTrangIDParameter = tinhTrangID.HasValue ?
            new ObjectParameter("TinhTrangID", tinhTrangID) :
            new ObjectParameter("TinhTrangID", typeof(int));


        var nhanVienIDParameter = nhanVienID.HasValue ?
            new ObjectParameter("NhanVienID", nhanVienID) :
            new ObjectParameter("NhanVienID", typeof(int));


        var ngayDuyetParameter = ngayDuyet.HasValue ?
            new ObjectParameter("NgayDuyet", ngayDuyet) :
            new ObjectParameter("NgayDuyet", typeof(System.DateTime));


        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("GhiChu", ghiChu) :
            new ObjectParameter("GhiChu", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NTCarteTemp_Update", iDDTTParameter, capDuyetParameter, tinhTrangIDParameter, nhanVienIDParameter, ngayDuyetParameter, ghiChuParameter);
    }


    public virtual int sp_handle_byIDCTTT(Nullable<int> idttt)
    {

        var idtttParameter = idttt.HasValue ?
            new ObjectParameter("idttt", idttt) :
            new ObjectParameter("idttt", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_handle_byIDCTTT", idtttParameter);
    }


    public virtual int sp_handle_byIDTTT(Nullable<int> idttt)
    {

        var idtttParameter = idttt.HasValue ?
            new ObjectParameter("idttt", idttt) :
            new ObjectParameter("idttt", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_handle_byIDTTT", idtttParameter);
    }


    public virtual int NT_DetailCarteTemporaire_delete_ByIDTTT(Nullable<int> idttt)
    {

        var idtttParameter = idttt.HasValue ?
            new ObjectParameter("idttt", idttt) :
            new ObjectParameter("idttt", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_DetailCarteTemporaire_delete_ByIDTTT", idtttParameter);
    }


    public virtual int NT_handle_Delete_byIDCTTT(Nullable<int> idttt)
    {

        var idtttParameter = idttt.HasValue ?
            new ObjectParameter("idttt", idttt) :
            new ObjectParameter("idttt", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_handle_Delete_byIDCTTT", idtttParameter);
    }


    public virtual int NT_handle_Dlete_byIDTTT(Nullable<int> idttt)
    {

        var idtttParameter = idttt.HasValue ?
            new ObjectParameter("idttt", idttt) :
            new ObjectParameter("idttt", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_handle_Dlete_byIDTTT", idtttParameter);
    }


    public virtual int NT_handle_Delete_byIDTTT(Nullable<int> idttt)
    {

        var idtttParameter = idttt.HasValue ?
            new ObjectParameter("idttt", idttt) :
            new ObjectParameter("idttt", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NT_handle_Delete_byIDTTT", idtttParameter);
    }


    public virtual ObjectResult<NT_CarteTemporaire_search_Result> NT_CarteTemporaire_search(Nullable<System.DateTime> begin, Nullable<System.DateTime> end, Nullable<int> nTID)
    {

        var beginParameter = begin.HasValue ?
            new ObjectParameter("begin", begin) :
            new ObjectParameter("begin", typeof(System.DateTime));


        var endParameter = end.HasValue ?
            new ObjectParameter("end", end) :
            new ObjectParameter("end", typeof(System.DateTime));


        var nTIDParameter = nTID.HasValue ?
            new ObjectParameter("NTID", nTID) :
            new ObjectParameter("NTID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NT_CarteTemporaire_search_Result>("NT_CarteTemporaire_search", beginParameter, endParameter, nTIDParameter);
    }

}

}

