//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsPartner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EPORTAL_UNISEntities : DbContext
    {
        public EPORTAL_UNISEntities()
            : base("name=EPORTAL_UNISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogUNIS> LogUNIS { get; set; }
    
        public virtual int LogUNIS_insert(string maThe, string hoTen, string maNT, string tenNT, string ngay, string gio, string mQT, string cCCD, Nullable<int> isNT)
        {
            var maTheParameter = maThe != null ?
                new ObjectParameter("MaThe", maThe) :
                new ObjectParameter("MaThe", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var maNTParameter = maNT != null ?
                new ObjectParameter("MaNT", maNT) :
                new ObjectParameter("MaNT", typeof(string));
    
            var tenNTParameter = tenNT != null ?
                new ObjectParameter("TenNT", tenNT) :
                new ObjectParameter("TenNT", typeof(string));
    
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            var gioParameter = gio != null ?
                new ObjectParameter("Gio", gio) :
                new ObjectParameter("Gio", typeof(string));
    
            var mQTParameter = mQT != null ?
                new ObjectParameter("MQT", mQT) :
                new ObjectParameter("MQT", typeof(string));
    
            var cCCDParameter = cCCD != null ?
                new ObjectParameter("CCCD", cCCD) :
                new ObjectParameter("CCCD", typeof(string));
    
            var isNTParameter = isNT.HasValue ?
                new ObjectParameter("isNT", isNT) :
                new ObjectParameter("isNT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LogUNIS_insert", maTheParameter, hoTenParameter, maNTParameter, tenNTParameter, ngayParameter, gioParameter, mQTParameter, cCCDParameter, isNTParameter);
        }
    
        public virtual ObjectResult<LogUNIS_Select_Result> LogUNIS_Select(string maThe, string ngay, string gio)
        {
            var maTheParameter = maThe != null ?
                new ObjectParameter("MaThe", maThe) :
                new ObjectParameter("MaThe", typeof(string));
    
            var ngayParameter = ngay != null ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(string));
    
            var gioParameter = gio != null ?
                new ObjectParameter("Gio", gio) :
                new ObjectParameter("Gio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LogUNIS_Select_Result>("LogUNIS_Select", maTheParameter, ngayParameter, gioParameter);
        }
    
        public virtual ObjectResult<LogUNIS_Query_Result> LogUNIS_Query(string begind, string endd)
        {
            var begindParameter = begind != null ?
                new ObjectParameter("begind", begind) :
                new ObjectParameter("begind", typeof(string));
    
            var enddParameter = endd != null ?
                new ObjectParameter("endd", endd) :
                new ObjectParameter("endd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LogUNIS_Query_Result>("LogUNIS_Query", begindParameter, enddParameter);
        }
    
        public virtual ObjectResult<LogUNIS_Check_Result> LogUNIS_Check(string cCCD, string ngay_HT, string ngay_QK)
        {
            var cCCDParameter = cCCD != null ?
                new ObjectParameter("CCCD", cCCD) :
                new ObjectParameter("CCCD", typeof(string));
    
            var ngay_HTParameter = ngay_HT != null ?
                new ObjectParameter("Ngay_HT", ngay_HT) :
                new ObjectParameter("Ngay_HT", typeof(string));
    
            var ngay_QKParameter = ngay_QK != null ?
                new ObjectParameter("Ngay_QK", ngay_QK) :
                new ObjectParameter("Ngay_QK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LogUNIS_Check_Result>("LogUNIS_Check", cCCDParameter, ngay_HTParameter, ngay_QKParameter);
        }
    }
}
