
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsPartner
{

using System;
    using System.Collections.Generic;
    
public partial class NT_CardTemp
{

    public int IDThe { get; set; }

    public string MaThe { get; set; }

    public string TenThe { get; set; }

    public string UserID { get; set; }

    public string EmployeeID { get; set; }

    public Nullable<int> IDCong { get; set; }

}

}
