
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsPartner
{

using System;
    using System.Collections.Generic;
    
public partial class NT_ContactEquipment
{

    public int IDTBNT { get; set; }

    public string NameEquipment { get; set; }

    public string IndentifierContact { get; set; }

    public string BienSoXe { get; set; }

    public int IDContact { get; set; }

    public string Operator { get; set; }

    public int IDDepartment { get; set; }

    public Nullable<int> Cavet { get; set; }

    public Nullable<System.DateTime> NgayHetHanDK { get; set; }

    public Nullable<System.DateTime> NgayHetHanKD { get; set; }

    public Nullable<System.DateTime> NgayHetHanBHX { get; set; }

    public Nullable<int> CCHV { get; set; }

    public Nullable<System.DateTime> NgayHetHanTAT { get; set; }

    public Nullable<System.DateTime> NgayHetHanVCHHChayNo { get; set; }

    public Nullable<System.DateTime> NgayHetHanCNKD { get; set; }

    public string ChungChiPCCCCNCH { get; set; }

    public string ChungChiVCHHNHCN { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public string KhuVucThiCong { get; set; }

    public string NguoiNhap { get; set; }

    public Nullable<int> TinhTrang { get; set; }

    public string GhiChu { get; set; }

    public string FileUpload { get; set; }

    public int IDMDD { get; set; }

    public string SoKhung { get; set; }

    public Nullable<System.DateTime> ThoiHanTheTu { get; set; }

    public Nullable<System.DateTime> ThoiHanTheRVTX { get; set; }

    public string CapMoi { get; set; }

    public string GiaHan { get; set; }

    public string MatThe { get; set; }

    public string CapNhatThongTin { get; set; }

    public string BaoLanh { get; set; }

    public Nullable<System.DateTime> NgayChinhSua { get; set; }

    public string FileTheTu { get; set; }

}

}
