
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsPartner
{

using System;
    using System.Collections.Generic;
    
public partial class NT_CarteTemporaire
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NT_CarteTemporaire()
    {

        this.NT_DetailCarteTemporaire = new HashSet<NT_DetailCarteTemporaire>();

    }


    public int IDTTT { get; set; }

    public string NoiDung { get; set; }

    public Nullable<int> NguoiTaoID { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<int> TinhTrang { get; set; }

    public Nullable<int> NTID { get; set; }

    public Nullable<int> PhongBanID { get; set; }

    public string HangMuc { get; set; }

    public Nullable<System.DateTime> ThoiHan { get; set; }

    public string GhiChu { get; set; }

    public Nullable<int> isNT { get; set; }

    public Nullable<int> KyTruoc { get; set; }

    public string FileHosoDK { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NT_DetailCarteTemporaire> NT_DetailCarteTemporaire { get; set; }

}

}
