
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsPartner
{

using System;
    using System.Collections.Generic;
    
public partial class NT_Handle
{

    public int IDXL { get; set; }

    public Nullable<int> IDTTT { get; set; }

    public Nullable<int> IDCTTTT { get; set; }

    public Nullable<int> NguoiXuLy { get; set; }

    public Nullable<System.DateTime> ThoiGianXuLy { get; set; }

    public Nullable<int> IDThe { get; set; }

}

}
