
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsPartner
{

using System;
    using System.Collections.Generic;
    
public partial class NT_HistoryBlackList
{

    public int IDHis { get; set; }

    public Nullable<int> NVVPID { get; set; }

    public Nullable<System.DateTime> NgayUpdate { get; set; }

    public Nullable<int> IDNVUpdate { get; set; }

    public Nullable<int> StatusUpdate { get; set; }

}

}
