
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsPartner
{

using System;
    using System.Collections.Generic;
    
public partial class NT_HoatDongNV
{

    public int IDHD { get; set; }

    public Nullable<int> IDNVNT { get; set; }

    public Nullable<int> IDNT { get; set; }

    public Nullable<System.DateTime> NgayCap { get; set; }

    public Nullable<System.DateTime> HanSuDung { get; set; }

    public string IDKV { get; set; }

    public Nullable<int> IDCA { get; set; }

    public string GhiChu { get; set; }

}

}
