
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsPartner
{

using System;
    using System.Collections.Generic;
    
public partial class NT_MaDinhDanh
{

    public int IDDD { get; set; }

    public string MaDinhDanh { get; set; }

    public string TenMaDinhDanh { get; set; }

}

}
