
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsPartner
{

using System;
    using System.Collections.Generic;
    
public partial class NT_NhanVienVP
{

    public int IDNVVP { get; set; }

    public string HoTen { get; set; }

    public string CCCD { get; set; }

    public string CMND { get; set; }

    public Nullable<System.DateTime> NgaySinh { get; set; }

    public string LyDoCam { get; set; }

    public string GhiChu { get; set; }

    public Nullable<System.DateTime> CreateDay { get; set; }

    public Nullable<int> CreateIDNV { get; set; }

    public Nullable<int> TinhTrang { get; set; }

}

}
