
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsPartner
{

using System;
    using System.Collections.Generic;
    
public partial class NT_UserTemp
{

    public int ID { get; set; }

    public string UserName { get; set; }

    public string MatKhau { get; set; }

    public Nullable<int> IDNT { get; set; }

    public Nullable<int> TinhTrang { get; set; }

    public string ChuKy { get; set; }

}

}
