//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsEquipment
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_LoiSuCoTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NV_LoiSuCoTB()
        {
            this.NV_QuanLyThietBi = new HashSet<NV_QuanLyThietBi>();
        }
    
        public int IDSC { get; set; }
        public string TenLoiSC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NV_QuanLyThietBi> NV_QuanLyThietBi { get; set; }
    }
}
