//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsEquipment
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_QuanLyThietBi
    {
        public int IDQLTB { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public string ServiceTag { get; set; }
        public Nullable<int> IDTB { get; set; }
        public string MaNV { get; set; }
        public string Phone { get; set; }
        public Nullable<int> IDSC { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> NgayXL { get; set; }
        public Nullable<System.DateTime> NgayHT { get; set; }
        public Nullable<System.DateTime> NgayNM { get; set; }
        public string GhiChu { get; set; }
        public string AdminNM { get; set; }
    
        public virtual NV_LoiSuCoTB NV_LoiSuCoTB { get; set; }
        public virtual NV_ThietBi NV_ThietBi { get; set; }
    }
}
