//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsPublish
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPORTAL_DOCUMENTEntities : DbContext
    {
        public EPORTAL_DOCUMENTEntities()
            : base("name=EPORTAL_DOCUMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VB_DetailDocument> VB_DetailDocument { get; set; }
        public virtual DbSet<VB_Document> VB_Document { get; set; }
    }
}
