//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsPublish
{
    using System;
    using System.Collections.Generic;
    
    public partial class VB_Document
    {
        public int IDVB { get; set; }
        public string TenVB { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<int> IDPage { get; set; }
        public Nullable<int> IDLoai { get; set; }
    }
}
