//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsPublish
{
    using System;
    using System.Collections.Generic;
    
    public partial class VB_DetailDocument
    {
        public int IDCTVB { get; set; }
        public Nullable<int> IDVB { get; set; }
        public string SoVB { get; set; }
        public string NoiDungVB { get; set; }
        public Nullable<System.DateTime> NgayVB { get; set; }
        public Nullable<System.DateTime> NgayBĐ { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public string TenFile { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
