//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsServey
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDKNT
    {
        public int ID { get; set; }
        public Nullable<int> IDSV { get; set; }
        public Nullable<int> IDOT { get; set; }
        public Nullable<int> IDNguoiThan { get; set; }
        public Nullable<int> IDGroup { get; set; }
    }
}
