//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsServey
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDKNguoiThan
    {
        public int ID { get; set; }
        public Nullable<int> IDNV { get; set; }
        public Nullable<int> IDNguoiThan { get; set; }
        public string HoTen { get; set; }
        public string DienThoai { get; set; }
        public Nullable<int> IDSV { get; set; }
        public Nullable<int> isCom { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public Nullable<int> IDDC { get; set; }
        public string NamSinh { get; set; }
        public string QuanHe { get; set; }
        public string GhiChu { get; set; }
    }
}
