//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsServey
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EPORTAL_SERVEYEntities : DbContext
    {
        public EPORTAL_SERVEYEntities()
            : base("name=EPORTAL_SERVEYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeServey> EmployeeServeys { get; set; }
        public virtual DbSet<ListServey> ListServeys { get; set; }
        public virtual DbSet<OptionServey> OptionServeys { get; set; }
        public virtual DbSet<PartTogether> PartTogethers { get; set; }
        public virtual DbSet<ResultServey> ResultServeys { get; set; }
        public virtual DbSet<CTKhaoSat> CTKhaoSats { get; set; }
        public virtual DbSet<GroupKhaoSat> GroupKhaoSats { get; set; }
        public virtual DbSet<DiaDiem> DiaDiems { get; set; }
        public virtual DbSet<ChiTietDKNT> ChiTietDKNTs { get; set; }
        public virtual DbSet<CTDKNguoiThan> CTDKNguoiThans { get; set; }
        public virtual DbSet<GhiChu> GhiChus { get; set; }
    
        public virtual int EmployeeServey_delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeServey_delete", iDParameter);
        }
    
        public virtual int EmployeeServey_insert(Nullable<int> iDNV, Nullable<int> iDSV, Nullable<int> menuOT)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var menuOTParameter = menuOT.HasValue ?
                new ObjectParameter("MenuOT", menuOT) :
                new ObjectParameter("MenuOT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeServey_insert", iDNVParameter, iDSVParameter, menuOTParameter);
        }
    
        public virtual ObjectResult<EmployeeServey_selectNV_Result> EmployeeServey_selectNV(Nullable<int> iDNV, Nullable<int> iDSV)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeServey_selectNV_Result>("EmployeeServey_selectNV", iDNVParameter, iDSVParameter);
        }
    
        public virtual int EmployeeServey_update(Nullable<int> iD, Nullable<int> iDNV, Nullable<int> iDSV, Nullable<int> menuOT)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var menuOTParameter = menuOT.HasValue ?
                new ObjectParameter("MenuOT", menuOT) :
                new ObjectParameter("MenuOT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeServey_update", iDParameter, iDNVParameter, iDSVParameter, menuOTParameter);
        }
    
        public virtual int EmployeeServey_updateOtion(Nullable<int> iDNV, Nullable<int> iDSV, Nullable<int> oTID, Nullable<bool> xNSV, Nullable<int> menuOT)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var oTIDParameter = oTID.HasValue ?
                new ObjectParameter("OTID", oTID) :
                new ObjectParameter("OTID", typeof(int));
    
            var xNSVParameter = xNSV.HasValue ?
                new ObjectParameter("XNSV", xNSV) :
                new ObjectParameter("XNSV", typeof(bool));
    
            var menuOTParameter = menuOT.HasValue ?
                new ObjectParameter("MenuOT", menuOT) :
                new ObjectParameter("MenuOT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeServey_updateOtion", iDNVParameter, iDSVParameter, oTIDParameter, xNSVParameter, menuOTParameter);
        }
    
        public virtual int EmployeeServey_updateXN(Nullable<int> iD, Nullable<bool> xNSV)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var xNSVParameter = xNSV.HasValue ?
                new ObjectParameter("XNSV", xNSV) :
                new ObjectParameter("XNSV", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeServey_updateXN", iDParameter, xNSVParameter);
        }
    
        public virtual int ListServey_delete(Nullable<int> iDSV)
        {
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListServey_delete", iDSVParameter);
        }
    
        public virtual int ListServey_insert(string contentSV, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<bool> statusSV)
        {
            var contentSVParameter = contentSV != null ?
                new ObjectParameter("ContentSV", contentSV) :
                new ObjectParameter("ContentSV", typeof(string));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var statusSVParameter = statusSV.HasValue ?
                new ObjectParameter("StatusSV", statusSV) :
                new ObjectParameter("StatusSV", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListServey_insert", contentSVParameter, startTimeParameter, endTimeParameter, statusSVParameter);
        }
    
        public virtual ObjectResult<ListServey_selectNV_Result> ListServey_selectNV(Nullable<int> iDNV, Nullable<System.DateTime> timeNow)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var timeNowParameter = timeNow.HasValue ?
                new ObjectParameter("TimeNow", timeNow) :
                new ObjectParameter("TimeNow", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListServey_selectNV_Result>("ListServey_selectNV", iDNVParameter, timeNowParameter);
        }
    
        public virtual int ListServey_update(Nullable<int> iDSV, string contentSV, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<bool> statusSV)
        {
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var contentSVParameter = contentSV != null ?
                new ObjectParameter("ContentSV", contentSV) :
                new ObjectParameter("ContentSV", typeof(string));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var statusSVParameter = statusSV.HasValue ?
                new ObjectParameter("StatusSV", statusSV) :
                new ObjectParameter("StatusSV", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListServey_update", iDSVParameter, contentSVParameter, startTimeParameter, endTimeParameter, statusSVParameter);
        }
    
        public virtual int OptionServey_create(string contentOT, Nullable<int> iDSV, string filePath, Nullable<int> orderBy)
        {
            var contentOTParameter = contentOT != null ?
                new ObjectParameter("ContentOT", contentOT) :
                new ObjectParameter("ContentOT", typeof(string));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("FilePath", filePath) :
                new ObjectParameter("FilePath", typeof(string));
    
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OptionServey_create", contentOTParameter, iDSVParameter, filePathParameter, orderByParameter);
        }
    
        public virtual int OptionServey_delete(Nullable<int> iDOT)
        {
            var iDOTParameter = iDOT.HasValue ?
                new ObjectParameter("IDOT", iDOT) :
                new ObjectParameter("IDOT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OptionServey_delete", iDOTParameter);
        }
    
        public virtual ObjectResult<OptionServey_selectOT_Result> OptionServey_selectOT(Nullable<int> iDSV)
        {
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OptionServey_selectOT_Result>("OptionServey_selectOT", iDSVParameter);
        }
    
        public virtual int OptionServey_update(Nullable<int> iDOT, string contentOT, Nullable<int> iDSV, string filePath, Nullable<int> orderBy)
        {
            var iDOTParameter = iDOT.HasValue ?
                new ObjectParameter("IDOT", iDOT) :
                new ObjectParameter("IDOT", typeof(int));
    
            var contentOTParameter = contentOT != null ?
                new ObjectParameter("ContentOT", contentOT) :
                new ObjectParameter("ContentOT", typeof(string));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("FilePath", filePath) :
                new ObjectParameter("FilePath", typeof(string));
    
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OptionServey_update", iDOTParameter, contentOTParameter, iDSVParameter, filePathParameter, orderByParameter);
        }
    
        public virtual int PartTogether_delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PartTogether_delete", iDParameter);
        }
    
        public virtual int PartTogether_insert(Nullable<int> iDNV, string hoTen, Nullable<System.DateTime> namSinh, Nullable<int> iDESV, string re, Nullable<bool> isCom, string note)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var namSinhParameter = namSinh.HasValue ?
                new ObjectParameter("NamSinh", namSinh) :
                new ObjectParameter("NamSinh", typeof(System.DateTime));
    
            var iDESVParameter = iDESV.HasValue ?
                new ObjectParameter("IDESV", iDESV) :
                new ObjectParameter("IDESV", typeof(int));
    
            var reParameter = re != null ?
                new ObjectParameter("Re", re) :
                new ObjectParameter("Re", typeof(string));
    
            var isComParameter = isCom.HasValue ?
                new ObjectParameter("isCom", isCom) :
                new ObjectParameter("isCom", typeof(bool));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PartTogether_insert", iDNVParameter, hoTenParameter, namSinhParameter, iDESVParameter, reParameter, isComParameter, noteParameter);
        }
    
        public virtual ObjectResult<PartTogether_selectCom_Result> PartTogether_selectCom(Nullable<int> iDESV, Nullable<bool> isCom)
        {
            var iDESVParameter = iDESV.HasValue ?
                new ObjectParameter("IDESV", iDESV) :
                new ObjectParameter("IDESV", typeof(int));
    
            var isComParameter = isCom.HasValue ?
                new ObjectParameter("isCom", isCom) :
                new ObjectParameter("isCom", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PartTogether_selectCom_Result>("PartTogether_selectCom", iDESVParameter, isComParameter);
        }
    
        public virtual int PartTogether_update(Nullable<int> iD, Nullable<int> iDNV, string hoTen, Nullable<System.DateTime> namSinh, Nullable<int> iDESV, string re, Nullable<bool> isCom, string note)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var namSinhParameter = namSinh.HasValue ?
                new ObjectParameter("NamSinh", namSinh) :
                new ObjectParameter("NamSinh", typeof(System.DateTime));
    
            var iDESVParameter = iDESV.HasValue ?
                new ObjectParameter("IDESV", iDESV) :
                new ObjectParameter("IDESV", typeof(int));
    
            var reParameter = re != null ?
                new ObjectParameter("Re", re) :
                new ObjectParameter("Re", typeof(string));
    
            var isComParameter = isCom.HasValue ?
                new ObjectParameter("isCom", isCom) :
                new ObjectParameter("isCom", typeof(bool));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PartTogether_update", iDParameter, iDNVParameter, hoTenParameter, namSinhParameter, iDESVParameter, reParameter, isComParameter, noteParameter);
        }
    
        public virtual int ResultServey_create(Nullable<int> iDES, Nullable<int> iDSV, Nullable<int> iDOT, Nullable<int> statusRS)
        {
            var iDESParameter = iDES.HasValue ?
                new ObjectParameter("IDES", iDES) :
                new ObjectParameter("IDES", typeof(int));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var iDOTParameter = iDOT.HasValue ?
                new ObjectParameter("IDOT", iDOT) :
                new ObjectParameter("IDOT", typeof(int));
    
            var statusRSParameter = statusRS.HasValue ?
                new ObjectParameter("StatusRS", statusRS) :
                new ObjectParameter("StatusRS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ResultServey_create", iDESParameter, iDSVParameter, iDOTParameter, statusRSParameter);
        }
    
        public virtual int ResultServey_update(Nullable<int> iD, Nullable<int> iDES, Nullable<int> iDSV, Nullable<int> iDOT, Nullable<int> statusRS)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iDESParameter = iDES.HasValue ?
                new ObjectParameter("IDES", iDES) :
                new ObjectParameter("IDES", typeof(int));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var iDOTParameter = iDOT.HasValue ?
                new ObjectParameter("IDOT", iDOT) :
                new ObjectParameter("IDOT", typeof(int));
    
            var statusRSParameter = statusRS.HasValue ?
                new ObjectParameter("StatusRS", statusRS) :
                new ObjectParameter("StatusRS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ResultServey_update", iDParameter, iDESParameter, iDSVParameter, iDOTParameter, statusRSParameter);
        }
    
        public virtual int RsultServey_delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RsultServey_delete", iDParameter);
        }
    
        public virtual int CTKhaoSat_delete(Nullable<int> iDSV, Nullable<int> iDNV)
        {
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CTKhaoSat_delete", iDSVParameter, iDNVParameter);
        }
    
        public virtual int CTKhaoSat_insert(Nullable<int> iDSV, Nullable<int> iDOT, Nullable<int> iDNV, Nullable<int> iDGroup)
        {
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var iDOTParameter = iDOT.HasValue ?
                new ObjectParameter("IDOT", iDOT) :
                new ObjectParameter("IDOT", typeof(int));
    
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var iDGroupParameter = iDGroup.HasValue ?
                new ObjectParameter("IDGroup", iDGroup) :
                new ObjectParameter("IDGroup", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CTKhaoSat_insert", iDSVParameter, iDOTParameter, iDNVParameter, iDGroupParameter);
        }
    
        public virtual int EmployeeServey_updateDC(Nullable<int> iDNV, Nullable<int> iDSV, Nullable<int> iDDC)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var iDDCParameter = iDDC.HasValue ?
                new ObjectParameter("IDDC", iDDC) :
                new ObjectParameter("IDDC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeServey_updateDC", iDNVParameter, iDSVParameter, iDDCParameter);
        }
    
        public virtual int ChiTietDKNT_delete(Nullable<int> iDNguoiThan)
        {
            var iDNguoiThanParameter = iDNguoiThan.HasValue ?
                new ObjectParameter("IDNguoiThan", iDNguoiThan) :
                new ObjectParameter("IDNguoiThan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChiTietDKNT_delete", iDNguoiThanParameter);
        }
    
        public virtual int ChiTietDKNT_insert(Nullable<int> iDSV, Nullable<int> iDOT, Nullable<int> iDNguoiThan, Nullable<int> iDGroup)
        {
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var iDOTParameter = iDOT.HasValue ?
                new ObjectParameter("IDOT", iDOT) :
                new ObjectParameter("IDOT", typeof(int));
    
            var iDNguoiThanParameter = iDNguoiThan.HasValue ?
                new ObjectParameter("IDNguoiThan", iDNguoiThan) :
                new ObjectParameter("IDNguoiThan", typeof(int));
    
            var iDGroupParameter = iDGroup.HasValue ?
                new ObjectParameter("IDGroup", iDGroup) :
                new ObjectParameter("IDGroup", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChiTietDKNT_insert", iDSVParameter, iDOTParameter, iDNguoiThanParameter, iDGroupParameter);
        }
    
        public virtual int CTDKNguoiThan_delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CTDKNguoiThan_delete", iDParameter);
        }
    
        public virtual int CTDKNguoiThan_insert(Nullable<int> iDNV, Nullable<int> iDNguoiThan, string hoTen, string dienThoai, Nullable<int> iDSV, Nullable<int> isCom, Nullable<int> gioiTinh, Nullable<int> iDDC, string namSinh, string quanHe, string ghiChu, ObjectParameter iD)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var iDNguoiThanParameter = iDNguoiThan.HasValue ?
                new ObjectParameter("IDNguoiThan", iDNguoiThan) :
                new ObjectParameter("IDNguoiThan", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var isComParameter = isCom.HasValue ?
                new ObjectParameter("isCom", isCom) :
                new ObjectParameter("isCom", typeof(int));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(int));
    
            var iDDCParameter = iDDC.HasValue ?
                new ObjectParameter("IDDC", iDDC) :
                new ObjectParameter("IDDC", typeof(int));
    
            var namSinhParameter = namSinh != null ?
                new ObjectParameter("NamSinh", namSinh) :
                new ObjectParameter("NamSinh", typeof(string));
    
            var quanHeParameter = quanHe != null ?
                new ObjectParameter("QuanHe", quanHe) :
                new ObjectParameter("QuanHe", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CTDKNguoiThan_insert", iDNVParameter, iDNguoiThanParameter, hoTenParameter, dienThoaiParameter, iDSVParameter, isComParameter, gioiTinhParameter, iDDCParameter, namSinhParameter, quanHeParameter, ghiChuParameter, iD);
        }
    
        public virtual int CTDKNguoiThan_update(Nullable<int> iD, Nullable<int> iDNV, Nullable<int> iDNguoiThan, string hoTen, string dienThoai, Nullable<int> iDSV, Nullable<int> isCom, Nullable<int> gioiTinh, Nullable<int> iDDC, string namSinh, string quanHe, string ghiChu)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var iDNguoiThanParameter = iDNguoiThan.HasValue ?
                new ObjectParameter("IDNguoiThan", iDNguoiThan) :
                new ObjectParameter("IDNguoiThan", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var isComParameter = isCom.HasValue ?
                new ObjectParameter("isCom", isCom) :
                new ObjectParameter("isCom", typeof(int));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(int));
    
            var iDDCParameter = iDDC.HasValue ?
                new ObjectParameter("IDDC", iDDC) :
                new ObjectParameter("IDDC", typeof(int));
    
            var namSinhParameter = namSinh != null ?
                new ObjectParameter("NamSinh", namSinh) :
                new ObjectParameter("NamSinh", typeof(string));
    
            var quanHeParameter = quanHe != null ?
                new ObjectParameter("QuanHe", quanHe) :
                new ObjectParameter("QuanHe", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CTDKNguoiThan_update", iDParameter, iDNVParameter, iDNguoiThanParameter, hoTenParameter, dienThoaiParameter, iDSVParameter, isComParameter, gioiTinhParameter, iDDCParameter, namSinhParameter, quanHeParameter, ghiChuParameter);
        }
    
        public virtual int EmployeeServey_updateOT(Nullable<int> iDNV, Nullable<int> iDSV, Nullable<int> iDOT)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            var iDSVParameter = iDSV.HasValue ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(int));
    
            var iDOTParameter = iDOT.HasValue ?
                new ObjectParameter("IDOT", iDOT) :
                new ObjectParameter("IDOT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeServey_updateOT", iDNVParameter, iDSVParameter, iDOTParameter);
        }
    }
}
