//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.ModelsServey
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupKhaoSat
    {
        public int ID { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public Nullable<int> IDSV { get; set; }
        public string TenNhom { get; set; }
        public Nullable<int> isShowRe { get; set; }
        public Nullable<int> isChon { get; set; }
    }
}
