
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsServey
{

using System;
    using System.Collections.Generic;
    
public partial class ListServey
{

    public int IDSV { get; set; }

    public string ContentSV { get; set; }

    public Nullable<System.DateTime> StartTime { get; set; }

    public Nullable<System.DateTime> EndTime { get; set; }

    public Nullable<bool> StatusSV { get; set; }

}

}
