
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EPORTAL.ModelsServey
{

using System;
    using System.Collections.Generic;
    
public partial class OptionServey
{

    public int IDOT { get; set; }

    public string ContentOT { get; set; }

    public Nullable<int> IDSV { get; set; }

    public string FilePath { get; set; }

    public Nullable<int> OrderBy { get; set; }

    public Nullable<int> MaOT { get; set; }

    public Nullable<int> isShow { get; set; }

}

}
