//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_QuyenCT
    {
        public int IDQuyenCT { get; set; }
        public Nullable<int> IDQuyenHT { get; set; }
        public Nullable<int> IDController { get; set; }
        public Nullable<int> IDQuyenCN { get; set; }
        public Nullable<int> isActive { get; set; }
    
        public virtual A_ListController A_ListController { get; set; }
        public virtual A_QuyenCN A_QuyenCN { get; set; }
        public virtual A_QuyenHT A_QuyenHT { get; set; }
    }
}
