//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_NhomThuVienFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public L_NhomThuVienFile()
        {
            this.L_ThuVienFile = new HashSet<L_ThuVienFile>();
        }
    
        public int IDNhom { get; set; }
        public string TenNhomTV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<L_ThuVienFile> L_ThuVienFile { get; set; }
    }
}
