//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_ThuVienFile
    {
        public int ID { get; set; }
        public string TenTaiLieu { get; set; }
        public string FileName { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> IDNhom { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    
        public virtual L_NhomThuVienFile L_NhomThuVienFile { get; set; }
    }
}
